= ITC-2480 Assignment Details and Directions
This page is organized into sections based on the category of your final grade that the assignment will fall into. Be sure to check the syllabus for information about how the categories are weighted in your final grade.

== Lab Assignments
For each topic having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities for the module (except topics 13/14 which should be combined in a single report). Submissions are made through the ITC CLASS site. *Good lab reports in this class are typically 400-700 words long.* Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

* xref:lab1.adoc[Lab 1: Linux Installation and First Steps]
* xref:lab2.adoc[Lab 2: Command Line Basics, Filesystem Navigation]
* xref:lab3.adoc[Lab 3: User Accounts, Permissions, and Package Management]
* xref:lab4.adoc[Lab 4: Text Manipulation]
* xref:lab5.adoc[Lab 5: Webserver and PHP Installation and Use]
* xref:lab6.adoc[Lab 6: SQL Databases and Web Applications]
* xref:lab7.adoc[Lab 7: Firewall Configuration and System Security]
* xref:lab8.adoc[Lab 8: Linux System Administration Utilities]
* xref:lab9.adoc[Lab 9: DNS Server Installation and Configuration]
* xref:lab10.adoc[Lab 10: An Introduction to Containers]
* xref:lab11.adoc[Lab 11: Practical Applications of Containers]
* xref:lab12.adoc[Lab 12: Filesystem Management and Hardware Utilities]
* xref:lab13.adoc[Lab 13: BASH Scripting]
* xref:lab14.adoc[Lab 14: Python Scripting for System Administration]

== Homework, Activities & Participation 
* Participate in an online forum discussion (typically 3 quality posts or more) of each topic on the ITC CLASS site. See forum posting page for details. (up to 10 points each chapter based on quality)
* Weekly Progress Self-Evaluation - Complete on the ITC CLASS Server Website (10 points possible each week)

== Skills Based Final Exam
The Skills Final Exam is designed to test your ability to apply the concepts learned in this class and practiced in labs to common, real-world scenarios. You will start with an empty virtual machine and need to install Linux as well as perform many of the tasks practiced in lab acitivites though in slightly different ways or with different settings.

include::program-info:ROOT:partial$stdfooter.adoc[]