= ITC-2480 Syllabus
Course Name: Administering Linux Operating Systems +
Course Number: ITC-2830 +
Instructor: Dr. Ben Franske +
Term: Fall 2024 (8/26/2024-12/19/2024) +
Meetings: No required meetings +
Location: Online

== Instructor Contact Information
include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)
* ITC 1480 or Linux Essentials Certificate (see course notes).
* Placement into ENG 1108 or completion of both ENG 0099 and READ 0093/0094 with a grade of C or higher.

=== Course Description
Covers the installation, configuration and maintenance of Linux systems with an emphasis on server administration. A major focus of this course is learning the Linux command line interface for system administration tasks. Other topics involve providing network services such as routing, firewalls, DNS, DHCP, file, web, and email servers to network clients. 

=== Required Resources
* https://debian-handbook.info/get/now/[The Debian Administrator's Handbook (Debian 10 Edition) by Raphaël Hertzog and Roland Mas] (ISBN: 979-1091414197) Available Free Online!
* http://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download[The Linux Command Line (2nd Edition or 5th Internet Edition) by William Shotts] (ISBN: 978-1593279523) Available Free Online!
* Various Online Readings (see course assignments page)

=== Optional Resources
No optional resources have been suggested for this course.

=== Course Website(s)
* ITC Info (https://info.ihitc.net)
* ITC Class Server (https://class.ihitc.net - access through link in D2L to sign in)

== Lab Time
All lab activities can be completed remotely but campus ITC labs will be available for your use during during office hours on a first come, first served basis. Open lab time may also be available under the supervision of the lab assistant, see the xref:program-info:ROOT:facstaff.adoc[faculty and staff page] for lab assistant contact information to reserve times. Students who do not show up for lab hours they have scheduled may be restricted from reserving lab hours in the future. 

== Course Objectives
Students will be able to:

* Determine and configure hardware settings
* Explain, configure and troubleshoot Linux booting
* Change runlevels and shutdown or reboot the system
* Design an appropriate hard disk layout
* Install a boot manager
* Use a package management system
* Work effectively on the command line
* Perform basic file management
* Use streams, pipes and redirects
* Create, monitor and kill processes
* Perform basic file editing operations with vi
* Create partitions and filesystems
* Maintain the integrity of filesystems
* Control mounting and unmounting of filesystems
* Manage file permissions and ownership
* Create and change hard and symbolic links
* Find system files and place files in the correct location
* Customize and use the shell environment
* Customize or write simple scripts
* Perform basic SQL data management
* Manage user and group accounts and related system files
* Schedule automated administration tasks
* Configure and view system logging
* Demonstrate an understanding of Linux networking fundamentals
* Configure and modify network settings
* Perform basic network troubleshooting
* Configure a DNS client and basic DNS server
* Perform security administration tasks
* Setup host security
* Secure data with encryption
* Setup a basic Linux router and firewall system
* Install and configure a basic webserver
* Install and configure a database driven web application
* Install and configure a basic DHCP server
* Write and modify simple shell scripts
* Write and modify scripts in Python or Perl
* Utilize SSH for remote access to a system
* Practice business soft skills including written, active listening, and oral presentation

== Course Design
This course will be taught as an online course. You will be responsible for completing required readings in the textbook or online, watching tutorial videos, listening to recorded podcasts, completing labs in the IHCC virtual lab environment, participating in online discussions, and completing online exams. 

== Assignments and Grading
Grades will be determined by performance on lab exercises, participation, and a skills exam. A description of assignments and directions for assignments are available from the course website. It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your course grade depending on the type of the assignment.

=== Late Assignments and Extensions
If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor. 

=== Grading Scale
[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability
Grades for this course are calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Lab Assignments 
|50%
|Skills Based Final Exam
|25%
|Homework, Activities & Participation 
|25% 
|===

Mid-Term grades are not officially distributed but assignment scores are made available in the online grade book as assignments are graded and you may calculate your current course grade at any time using the above instructions and weighting. It is strongly suggested that if you want to know where you stand in the class you re-create your own copy of the gradebook with appropriate weights in a spreadsheet program such as OpenOffice Calc, Microsoft Excel, or Google Sheets where you can estimate scores you will likely get on future assignments and run other "what-if" scenarios.

Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 
=== Extra Credit
Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Extra credit will be added to the Homework, Activities & Participation category. 

== Course and Campus Policies
include::ROOT:partial$campus-policies.adoc[] 

== Updates to this Syllabus
The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]