= ITC-2480 Syllabus
Course Name: Administering Linux Operating Systems
Course Number: ITC-2830
Instructor: Dr. Ben Franske
Term: Spring 2022 (1/12/2022-5/11/2022)
Meetings: No required meetings
Location: Online

== Instructor Contact Information
*E-mail:*
* ben@ihitc.net (when emailing please include your course number, section number and full name)

*Text Messaging/Chat:*
* Find me on Microsoft Teams, it's available as a Website, Desktop application, Android, and IOS application. To make the best use of it you are encouraged to have it installed on your computer as well as a smartphone.
** Access Instructions: Get instructions for installing the latest Office 365 apps on your computer which includes Teams and/or sign on to the Teams web app at office.com with <YourStarID>@go.minnstate.edu and/or sign in to the Microsoft Teams mobile app with <YourStarID>@go.minnstate.edu

*Office and Hours:*
* Online office hours (email during these times and we can setup a Zoom or phone call right away): Weds 11:00am-1:00pm, 2:30-4:00pm
* On campus office hours and lab assistance time (subject to change to online based on COVID-19 recommendations) look for me in the Business Building room B120 or B143: Tues 2:00-4:30pm
* Webcam/phone/in-person meetings also available other times by appointment.

*Phone:*
* Office: 651-450-3575 (leave a message with details and I will get back to you)

== General Course Information
=== Prerequisite(s)
* ITC 1480 or Linux Essentials Certificate (see course notes).
* Placement into ENG 1108 or completion of both ENG 0099 and READ 0093/0094 with a grade of C or higher.
=== Course Description
Covers the installation, configuration and maintenance of Linux systems with an emphasis on server administration. A major focus of this course is learning the Linux command line interface for system administration tasks. Other topics involve providing network services such as routing, firewalls, DNS, DHCP, file, web, and email servers to network clients. 
=== Required Resources
* https://debian-handbook.info/get/now/[The Debian Administrator's Handbook (Debian 10 Edition) by Raphaël Hertzog and Roland Mas] (ISBN: 979-1091414197) Available Free Online!
* http://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download[The Linux Command Line (2nd Edition or 5th Internet Edition) by William Shotts] (ISBN: 978-1593279523) Available Free Online!
* Various Online Readings (see course assignments page)
=== Optional Resources
No optional resources have been suggested for this course.
=== Course Website(s)
* ITC Info (https://info.ihitc.net)
* ITC Class Server (https://class.ihitc.net - access through link in D2L to sign in)
== Lab Time
All lab activities can be completed remotely but campus ITC labs will be available for your use during during office hours on a first come, first served basis. Open lab time may also be available under the supervision of the lab assistant, see the xref:program-information:ROOT:facstaff.adoc[faculty and staff page] for lab assistant contact information to reserve times. Students who do not show up for lab hours they have scheduled may be restricted from reserving lab hours in the future. 
== Course Objectives
Students will be able to:
* Determine and configure hardware settings
* Explain, configure and troubleshoot Linux booting
* Change runlevels and shutdown or reboot the system
* Design an appropriate hard disk layout
* Install a boot manager
* Use a package management system
* Work effectively on the command line
* Perform basic file management
* Use streams, pipes and redirects
* Create, monitor and kill processes
* Perform basic file editing operations with vi
* Create partitions and filesystems
* Maintain the integrity of filesystems
* Control mounting and unmounting of filesystems
* Manage file permissions and ownership
* Create and change hard and symbolic links
* Find system files and place files in the correct location
* Customize and use the shell environment
* Customize or write simple scripts
* Perform basic SQL data management
* Manage user and group accounts and related system files
* Schedule automated administration tasks
* Configure and view system logging
* Perform basic mail transfer agent administration
* Demonstrate an understanding of Linux networking fundamentals
* Configure and modify network settings
* Perform basic network troubleshooting
* Configure a DNS client and basic DNS server
* Perform security administration tasks
* Setup host security
* Secure data with encryption
* Setup a basic Linux router and firewall system
* Install and configure a SAMBA based fileserver
* Install and configure a basic webserver
* Install and configure a database driven web application
* Install and configure a basic DHCP server
* Write and modify simple shell scripts
* Write and modify scripts in Python or Perl
* Utilize SSH for remote access to a system
* Practice business soft skills including written, active listening, and oral presentation
* Document evidence of business skill practice in an electronic portfolio
== Course Design
This course will be taught as an online course. You will be responsible for completing required readings in the textbook or online, watching tutorial videos, listening to recorded podcasts, completing labs in the IHCC virtual lab environment, participating in online discussions, and completing online exams. 
== Assignments and Grading
Grades will be determined by performance on unit multiple-choice tests, lab exercises, participation, a skills exam, and a final exam. A description of assignments and directions for assignments are available from the course website. It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your course grade depending on the type of the assignment.
=== Late Assignments and Extensions
If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor. 
=== Grading Scale
[options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability
Grades for this course are calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
[options="header"]
|===
|Category |Percent of Final Grade
|Topic Assessments 
|20%
|Lab Assignments 
|30%
|Written Final Exam 
|15%
|Skills Based Final Exam 
|15%
|Homework, Activities & Participation 
|20% 
|===

Mid-Term grades are not officially distributed but assignment scores are made available in the online grade book as assignments are graded and you may calculate your current course grade at any time using the above instructions and weighting. It is strongly suggested that if you want to know where you stand in the class you re-create your own copy of the gradebook with appropriate weights in a spreadsheet program such as OpenOffice Calc, Microsoft Excel, or Google Sheets where you can estimate scores you will likely get on future assignments and run other "what-if" scenarios.

Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 
=== Extra Credit
Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Extra credit will be added to the Homework, Activities & Participation category. 

== Course and Campus Policies
=== Attendance
After the first class meeting formal attendance will not be taken; however, students are expected to arrive to class on time and participate in class. Students are expected to attend all sessions of each class in which they are enrolled. If attendance is a problem participation assignments may be given and included in the course grade. If an illness or emergency results in an absence, students should contact their instructors as soon as possible to determine if missed work can be completed. A student may receive a course grade of FN or NC after two consecutive weeks of unexcused absence at any time during the semester. Class attendance is defined as being physically present in the classroom. Online attendance is defined as having submitted an assignment, taken a quiz, or posted/made a course content-related comment on the discussion/chat board for the course in which the student is registered. 

=== Use and Access to Technology
You will need daily access to a high-speed internet connection (DSL, cable modem, 4G, fiber, or equivalent) and a modern computer to successfully complete this course. 

=== Academic Integrity (Plagiarism and Cheating)
Academic integrity is one of the most important values in higher education. This principle requires that each student's work represents his or her own personal efforts and that the student acknowledges the intellectual contributions of others. The foundation for this principle is student academic honesty. IHCC students are expected to honor the requirements of the College Academic Integrity Policy. The following are some examples of unacceptable academic practices that will be viewed as policy violations.

It is unacceptable to submit the work of another person as your own. If you quote, summarize, paraphrase, or use the ideas of another, you must accurately attribute that information. If you do not acknowledge the source, you are plagiarizing. Academic dishonesty also includes unauthorized collaboration on academic work; taking, acquiring, or using test materials without faculty permission; submitting the same assignment for multiple classes without instructor permission; taking an examination for another person and many other situations. If you are unsure whether you are plagiarizing or how to cite a source please ask an instructor or staff member for help prior to turning in the assignment.

In this course, the first offense of plagiarism and/or cheating will result in a score of zero on the assignment, quiz or test and reporting of the incident to college administration. Further plagiarism and/or cheating may result in immediate failure of the course and additional consequences determined by college administration.

If you have cheated in other ITC courses that will count as your first offense. In other words, if you have cheated in ITC courses before cheating in this course may result in immediately failing the course and additional consequences determined by college administration.

All instances of cheating will be reported to the college administration. In addition, plagiarism and cheating are covered by the Student Code of Conduct. Please see the Catalog or IHCC website for details. 

=== Withdrawing from the Course
Students must initiate requests for withdrawal from a course by filing the appropriate form with Enrollment Services. Students who stop attending classes without completing the withdrawal process may receive a grade of “F,” and are responsible for all tuition/fees associated with the course registration. The last day to withdraw from your course will be the date on which 80% of the course has elapsed. The last day to withdraw for each course can be viewed in E-Services by searching for the course at the following link: https://webproc.mnscu.edu/registration/search/basic.html?campusid=157. Click on the course title to view additional details about the course, including last day to withdraw. 

There are limits as to the latest date you can withdraw from the course and still receive a refund as well as the last date to withdraw from the course at all. Please see the Add, Drop and Withdraw page on the IHCC website: https://inverhills.edu/Registration/AddDropWithdraw.aspx
=== E-mail Communications
Recognizing the value and efficiency of communication between faculty/staff and students through electronic mail Inver Hills Community College has designated e-mail as an official mode of communication. At the same time, email raises some issues concerning security and the identity of each individual in an email exchange. Therefore, students are asked to regularly check and utilize the email address they have registered with the college. If your email address has changed it is your responsibility to make sure the college has an up-to date email address where you can be contacted. You should check your email on a regular basis as course changes and communications may be sent by email. 
=== Pass/Fail Grade Option
A student may elect to take a course on a pass/fail (P/F) grading basis by contacting the instructor within the first 5 business days of the semester, or within 1 business day of the start date for a course beginning after the first week of the semester. If the instructor approves, they will submit approval to the Enrollment Center. Not all courses are approved for students to elect the P/F grading method and there may be limits to the total number of classes which can be taken pass/fail in your degree or certificate program. Contact your instructor for details about what level of achievement in the course will be required to receive a pass in the course. 
=== Access and Accommodations
Inver Hills values diversity and inclusion; we are committed to fostering mutual respect and full participation for all students. My goal is to create a learning environment that is equitable, inclusive and welcoming. If any aspects of instruction or course design result in barriers to your inclusion or learning, please notify me. The Office of Accessibility Resources (OAR) provides reasonable accommodations and assistive technologies for students who encounter barriers in the learning environment. Services are available to students with a wide range of disabilities including, but not limited to, physical disabilities, medical conditions, learning disabilities, attention deficit disorder, depression, and anxiety. If you have already registered with OAR and have your Letter of Accommodation, please meet with me early in the course to discuss, plan, and implement your accommodations in the course. For additional information, please contact OAR located within the Learning Center (L207), 651-450-3884, accessibilityresources@inverhills.edu or https://www.inverhills.edu/LearningSupport/AccessibilityResources/index.aspx
=== Religious Accommodation Statement
In accordance with federal and state laws, Inver Hills Community College is committed to a policy of free expression and respect for the diversity of beliefs, including religious observances, among our academic community. It is the policy of the college to provide reasonable accommodations for students when religious beliefs and/or observances conflict with classroom activities or course requirements.

It is the responsibility of students to notify instructors of the need for accommodation at the beginning of the course or as soon as a situation arises. If a mutually agreed accommodation is not made, a student may initiate a complaint. The procedure for filing a complaint is described in the Catalog and on the Inver Hills website. The complaint must be filed within 15 days of a denied accommodation request. 
==Updates to this Syllabus
The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

Document Build Time: {localdatetime}
Page Version: {page-component-version}
