= ITC-2510 Assignment Details and Directions

== Lab & Homework Assignments

=== Packet Tracer Online Submissions
Each of these activities will be submitted using the Packet Tracer ScoreUP Online Submission process. Points will be earned for each submitted activity based on correctness and completion of the activity. You will see a completion percentage for each activity in the Packet Tracer software before submitting. Remember to submit through ScoreUP inside of Packet Tracer and to save for yourself a copy of your finished activity file in case it's requested by your instructor.

. PT 2.5.5 - Configure Initial Switch Settings (5 points)
. PT 2.7.6 - Implement Basic Connectivity (5 points)
. PT 2.9.1 - Basic Switch and End Device Configuration (5 points)
. PT 4.6.5 - Connect a Wired and Wireless LAN (5 points)
. PT 4.7.2 - Connect the Physical Layer (5 points)
. PT 10.1.4 - Configure Initial Router Settings (5 points)
. PT 10.3.4 - Connect a Router to a LAN (5 points)
. PT 10.3.5 - Troubleshoot Default Gateway Issues (5 points)
. PT 11.5.5 - Subnet and IPv4 Network (5 points)
. PT 11.7.5 - Subnetting Scenario (5 points)
. PT 11.9.3 - VLSM Design and Implementation Practice (5 points)
. PT 11.10.1 - Design and Implement a VLSM Addressing Scheme (5 points)
. PT 12.4.5 - Basic Device Configuration (5 points)
. PT 12.6.6 - Configure IPv6 Addressing (5 points)
. PT 12.9.1 - Implement a Subnetted IPv6 Addressing Scheme (5 points)
. PT 13.2.7 - Use Ping and Traceroute to Test Network Connectivity (5 points)
. PT 13.3.1 - Use ICMP to Test and Correct Network Connectivity (5 points)
. PT 16.4.6 - Configure Secure Passwords and SSH (5 points)
. PT 16.5.1 - Secure Network Devices (5 points)
. PT 17.7.6 - Troubleshoot Connectivity Issues (5 points)
. PT 17.8.2 - Skills Integration Challenge (15 points)
. PT 17.8.3 - Troubleshooting Challenge (15 points)

=== Lab Reports
For each module having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities listed below in the module. Submissions are made through the IHCC D2L site. You do not need to submit answers to the questions in the activities, those are for your own learning use only. Lab activities may include remote equipment access, campus equipment, or packet tracer activities. *Good lab reports in this class are typically 400-700 words long.* If you work with a partner on a lab you only need to submit a single lab report for the two of you but it must have both your names on it. Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

. Lab 2.3.8 - Navigate the IOS by Using Tera Term for Console Connectivity
. Lab 2.9.2 - Basic Switch and End Device Configuration
. PT 3.5.5 - Investigate the TCP/IP and OSI Models in Action
. Lab 3.7.10 - Use Wireshark to View Network Traffic
+
--
NOTE: In this lab activity you are going to use a `ping` command and watch the results in Wireshark. If the Internet connection you are working on has IPv6 connectivity you will see things like `Pinging google.com [2607:f8b0:4009:80a::200e]` instead of `Pinging google.com [142.250.190.78]`. If this is the case you can force an IPv4 ping using a command like `ping -4 google.com`.
--
. Lab 4.6.6 - View Wired and Wireless NIC Information
+
--
NOTE: Use a laptop computer for the wireless portion, the lab desktop computers only have wired connections.
--
. Lab 7.1.6 - Use Wireshark to Examine Ethernet Frames
. Lab 7.2.7 - View Network Device MAC Addresses
. Lab 7.3.7 - View the Switch MAC Address Table
. PT 9.1.3 - Identify MAC and IP Addresses
. PT 9.2.9 - Examine the ARP Table
. PT 9.3.4 - IPv6 Neighbor Discovery
. Lab 10.4.3 - Build a Switch and Router Network
. Lab 12.9.2 - Configure IPv6 Addresses on Network Devices
. PT 13.2.6 - Verify IPv4 and IPv6 Addressing
. Lab 13.3.2 - Use Ping and Traceroute to Test Network Connectivity
. PT 14.8.1 - TCP and UDP Communications
. Lab 15.4.8 - Observe DNS Resolution
. Lab 16.4.7 - Configure Network Devices with SSH
. Lab 16.5.2 - Secure Network Devices
. PT 17.5.9 - Interpret Show Command Output
. Lab 17.7.7 - Troubleshoot Connectivity Issues
. Lab 17.8.1 - Design and Build a Small Business Network
+
--
NOTE: Design your network in the Packet Tracer Software, in addition to your lab report upload your Packet Tracer File to the IHCC D2L site for this assignment.
--

=== Homework
Homework activities will require submitting the actual answers to each question in the activity and may require showing your work as well. Homework assignment are individual, you and your lab partner need to both turn them in separately even if you work on them together.

* Lab 11.6.6 - Calculate IPv4 Subnets (10 Points) - This activity will be submitted as a "quiz" on the IHCC D2L site where you will enter some of your answers from the activity into the quiz.
* Lab 11.10.2 - Design and Implement a VLSM Addressing Scheme (10 Points) - This activity will be submitted as a "quiz" on the IHCC D2L site where you will enter some of your answers from the activity into the quiz.
* Lab 12.7.4 - Identify IPv6 Addresses (10 Points) - This activity will be submitted as a "quiz" on the IHCC D2L site where you will enter some of your answers from the activity into the quiz.
* Participate in an online forum discussion (typically 3 quality posts or more) of each module on the IHCC D2L site. See the xref:forum-posting:index.adoc[forum posting page] for details. (up to 10 points each module based on quality)

TIP: Discussion forum posts are usually worth a larger portion of your final grade than most students expect! If you have not done discussion posts in one of Dr. Franske's classes before, or you want to try and score better on discussion forum postings, be sure to check out the xref:forum-posting:index.adoc[instructions for participating in forum discussions and example posts]!

== Participation Activities
Any participation activities completed in the course will go here. This falls into the participation category of your course grade. Note that participation activities are not always that you get all the points just for dong them. These are just activities which measure your participation and engagement in the class. How each activity is graded is noted after the activity in the list below.

* Complete a Course Introduction exam (20 points based on your score)
* Complete the online practice final exam (10 points for attempting)
* Complete the online Packet Tracer Practice Skills Assessment (10 points for attempting)
* Complete a weekly online check-in form or meet with the instructor during class to discuss course progress and ask questions (up to 10 points each based on progress)

== Module Assessments
You are responsible for completing all of the online module assessments listed below. These exams fall into the module assessments category of your course grade. *If you are not able to complete an exam by the due date listed on the course schedule it is your reponsibility to contact the instructor prior to the due date for the exam. Contacting the instructor after the due date for the exam will usually mean the late work policy will apply (see the syllabus).* For example, if the exam reports as not activated, or the website is down, you have lost Internet access, etc. contact the instructor as soon as possible for assistance.

* Module 1: Networking Today
* Module 2: Basic Switch and End Device Configuration
* Module 3: Protocols and Models
* Module 4: Physical Layer
* Module 5: Number Systems
* Module 6: Data Link Layer
* Module 7: Ethernet Switching
* Module 8: Network Layer
* Module 9: Address Resolution
* Module 10: Basic Router Configuration
* Module 11: IPv4 Addressing
* Module 12: IPv6 Addressing
* Module 13: ICMP
* Module 14: Transport Layer
* Module 15: Application Layer
* Module 16: Network Security Fundamentals
* Module 17: Build a Small Network

== Skills Final Exam
The Skills Final Exams are designed to test your ability to apply the concepts learned in this class and practiced in labs to common, real-world scenarios. There are two parts to this portion of your grade.

* Completing all parts of the online Packet Tracer Skills Assessment (PTSA) at home. You grade will be based on correctly completing all parts of the activity. You will be able to use outside resources for this part of the exam.
* Completing a lab equipment skills exam. You will not be able to use any resources other than those specified by your instructor on this part of the exam.

== Regular Final Exams
You will need to complete an online final exam

include::program-info:ROOT:partial$stdfooter.adoc[]