site:
  title: IHITC Info
  url: https://bfranske.github.io/ihitc-docs/
  start_page: program-info::index.adoc 
content:
  sources: 
  - url: https://github.com/bfranske/ihitc-docs.git
    start_paths: 
    - program-information/
    - franske-course-information/
    branches: HEAD
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
