site:
  title: IHITC Info
  url: https://bfranske.github.io/ihitc-docs/
  start_page: program-info::index.adoc 
content:
  sources: 
  - url: https://github.com/bfranske/ihitc-docs.git
    start_paths: 
    - program-information/
    - franske-course-information/
    - technical-information/
    - software-information/
    branches: ['{0..9}{0..9}{0..9}{0..9}.{0..9}{0..9}']
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
      - CNAME
  - path: .nojekyll
  - path: CNAME
    contents: |
      info.ihitc.net
urls:
  html_extension_style: drop
  latest_version_segment: current
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true