site:
  title: IHITC Info
  url: https://bfranske.github.io/ihitc-docs/
  start_page: program-info::index.adoc 
content:
  sources: 
  - url: https://github.com/bfranske/ihitc-docs.git
    start_paths: 
    - program-information/
    - franske-course-information/
    - technical-information/
    - software-information/
    branches: ['{0..9}{0..9}{0..9}{0..9}.{0..9}{0..9}']
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - CNAME
      - shakespeare.tar.gz
      - hello_2.10-3_amd64.deb
      - icecream_db.tar.gz
      - ITC-Passport-VPN.ovpn
      - .nojekyll
  - path: CNAME
    contents: |
      info.ihitc.net
  - path: shakespeare.tar.gz
    contents: ./static/shakespeare.tar.gz
  - path: hello_2.10-3_amd64.deb
    contents: ./static/hello_2.10-3_amd64.deb
  - path: icecream_db.tar.gz
    contents: ./static/icecream_db.tar.gz
  - path: ITC-Passport-VPN.ovpn
    contents: ./static/itc-passport-vpn.ovpn
  - path: .nojekyll
urls:
  html_extension_style: drop
  latest_version_segment: current
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true