= ITC-2621 Assignment Details and Directions

== Lab & Homework Assignments

=== Lab Reports
For each chapter having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities listed below in the chapter. Submissions are made through the NetAcad site. You do not need to submit answers to the questions in the activities, those are for your own learning use only. Lab activities may include remote equipment access or campus equipment. *Good lab reports in this class are typically 400-700 words long.* Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

[NOTE] 
.When Using Netlab Remote Lab System
==== 
* The login password for CAASP Pod PCs in Netlab is: Cisco123
====

. Lab 1.1.2 - Troubleshooting IPv4 and IPv6 Routing Issue 

+
--
NOTE: For some reason Cisco forgot to create VLAN 10 on switch D1 in the troubleshooting configurations. I have fixed this on some pods, but not all. You can easily fix it by creating VLAN 10 on switch D1 after loading the preset config for each ticket. This is not the problem you are supposed to find in any of the tickets, there are other problems.
--
. Lab 1.1.3 - Troubleshoot Static Routing
. Lab 2.1.2 - Implement EIGRP for IPv4
. Lab 3.1.2 - Implement Advanced EIGRP for IPv4 Features
. Lab 4.1.2 - Troubleshooting EIGRP for IPv4
. Lab 5.1.2 - Implement EIGRP for IPv6
. Lab 5.1.3 - Troubleshoot EIGRP for IPv6
. Lab 6.1.2 - Implement Single-Area OSPFv2
. Lab 7.1.2 - Implement Multi-Area OSPFv2
. Lab 7.1.3 - OSPFv2 Route Summarization and Filtering
. Lab 8.1.2 - Troubleshoot OSPFv2
. Lab 9.1.2 - Implement Multiarea OSPFv3
. Lab 10.1.2 - Troubleshoot OSPFv3
. Lab 11.1.2 - Implement eBGP for IPv4
. Lab 11.1.3 - Implement MP-BGP
. Lab 12.1.2 - Implement BGP Path Manipulation
. Lab 13.1.2 - Implement BGP Communities
. Lab 14.1.2 - Troubleshoot BGP
. Lab 15.1.2 - Control Routing Updates
. Lab 15.1.3 - Path Control Using PBR
. Lab 15.1.4 - Troubleshoot Route Maps and PBR
. Lab 16.1.2 - Configure Route Redistribution Between EIGRP and OSPF
. Lab 16.1.3 - Configure Route Redistribution Within the Same Interior Gateway Protocol
. Lab 16.1.4 - Implement Route Redistribution Between Multiple Protocols
. Lab 17.1.2 - Troubleshoot Route Redistribution
. Lab 18.1.2 - Implement VRF-Lite
. Lab 19.1.2 - Implement a GRE Tunnel
. Lab 19.1.3 - Implement a DMVPN Phase 1 Hub-to-Spoke Topology
. Lab 19.1.4 - Implement a DMVPN Phase 3 Spoke-to-Spoke Topology
. Lab 19.1.5 - Implement an IPv6 DMVPN Phase 3 Spoke-to-Spoke Topology
. Lab 20.1.2 - Configure Secure DMVPN Tunnels
. Lab 21.1.2 - Troubleshoot IPv4 ACLs
. Lab 21.1.3 - Troubleshoot IPv6 ACLs
. Lab 21.1.4 - Troubleshoot Prefix Lists
. Lab 22.1.2 - Troubleshoot IOS AAA
. Lab 22.1.3 - Troubleshoot uRPF
. Lab 22.1.4 - Troubleshoot CoPP
. Lab 23.1.2 - Troubleshoot Device Access and File Transfer
. Lab 23.1.3 - Troubleshoot SNMP and Logging Issues
. Lab 23.1.4 - Troubleshoot IP SLA and NetFlow

==== Homework

* Participate in an online forum discussion (typically 3 quality posts or more) of each chapter on the Cisco Netacad site. See the xref:forum-posting:index.adoc[forum posting page] for details. (up to 10 points each chapter based on quality)

TIP: Discussion forum posts are usually worth a larger portion of your final grade than most students expect! If you have not done discussion posts in one of Dr. Franske's classes before, or you want to try and score better on discussion forum postings, be sure to check out the xref:forum-posting:index.adoc[instructions for participating in forum discussions and example posts]!

=== Participation Activities
Any participation activities completed in the course will go here. This falls into the participation category of your course grade.

* Complete the online course feedback form (5 points for completing)
* Complete the online certification practice exam (10 points for attempting)

You must do one of the following choices at least once a week (up to 10 points each based on progress):

* Meet with the instructor online Tuesdays 6:00-8:30pm to discuss course progress and ask questions. *Note that you must send an email by 7pm on Tuesday if you want to meet after 7pm. I will only stay until 7pm unless someone has notified me they will be coming later*.
* Meet with the instructor at another time during the week scheduled in advance. *Availability is not guaranteed so you should schedule this early.*
* Submit a written statement on your progress in the course by email. You must meet the following requirements with your statement:
** It must be emailed to ben@ihitc.net
** The subject line on Tuesday of each week before 7:00pm. For weekly tracking purposes it cannot be sent before Tueday.
** The subject line must be "ITC-2621 Weekly Update"
** It must answer the following questions and should be about 300-400 words:
*** What is your full name
*** Where are you with the schedule? Are you on track, everything due done? Are you behind, how far? Are you ahead, how far?
*** What things did you learn this week?
*** How did any labs go for you this week?
*** What questions do you have about the content or course this week?

=== Unit Assessments
You are responsible for completing all of the online unit assessments listed below. Multiple chapters are included in single exams. These exams fall into the online assessments category of your course grade. 

* Chapters 1 - 5: Routing and EIGRP Exam
* Chapters 6 - 10: OSPF Exam
* Chapters 11 - 14: BGP Exam
* Chapters 15 - 17: Conditional Forwarding and Route Redistribution Exam
* Chapters 18 - 20: VPNs Exam
* Chapters 21 - 23: Infrastructure Security and Management Exam

=== Skills Final Exam
The Skills Final Exam is designed to test your ability to apply the concepts learned in this class and practiced in labs to common, real-world scenarios. Your grade in this category will be based on completing a lab equipment skills exam. You will not be able to use any resources other than those specified by your instructor on this part of the exam. 

Just like many of the topics in the class there will be *two parts to the skills exam in this course*:

* A configuration exercise skills exam
* A troubleshooting exercise skills exam

The Skills Final Exam must be completed on the IHCC Netlab system and has specific start and end dates specified on the course schedule. This is a timed activity which you will have no more than one Netlab 4 hour reservation (about 3 hours and 20 minutes) to complete _each_ one of the two parts to the exam. To maximize your available time it is suggested you start your reservation on an hour or half-hour. *You must do the configuration exercise before doing the troubleshooting exercise but can spread them out over two days if you wish.* Separate Netlab reservations must be made for each part of the exam (configuration and troubleshooting). You will be able to begin reserving slots in Netlab for this a few days in advance (so you can get the time you want). You must not spend more than a single 4 hour reservation working on each part of the exam and once you start each part of the exam you must work on it continuously, you cannot stop and then re-start the same part of the exam later.

* I strongly suggest making a 1 page "cheat sheet" for yourself of the common commands needed for configuring the routers and switches as required to complete the labs in CCNP ENARSI, this will help you if you have forgotten a particular command. You may also want to review and/or mark sections of the "CCNP Portable Command Guide" book you bought for this class as that is also a good resource when you're stuck.
NOTE: Assistance with issues will not be guaranteed outside of the normal work day/week so if you're concerned you may have issues during any portion of your exams you should plan to complete them during scheduled office or lab hours.

Breaking any of the following rules is considered cheating and could give you an unfair advantage on the exam so any evidence of them will result in a 0 on the entire skills exam:

* You are NOT allowed to ask anyone else for help, or seek out any copies of any part of the exams or solution keys to the exams in any format. You may use your class materials (textbook, my lecture videos, lab activity instructions, any notes you have made) and other websites/videos which are not providing individual assistance to you or exam specific answers though.
* You must NOT access a reservation with a date before the official start date of the exam or after the end date of the exam.
* You must NOT do the troubleshooting exercise before the configuration exercise.
* You must NOT stop a part of the exam and come back to it. All work for each part must be completed in a single reservation. You MAY take a break (even multiple days if desired) between the configuration and troubleshooting parts as long as both parts are complete before the official end date of the exam.
* If you have any questions about something, or if something is OK, or any other issues you must send an email to your instructor about it.

If you have any questions or issues please contact me as soon as possible. Remember that I'm here to help clarify anything you find confusing if I can. It never hurts to ask for help if you're stuck or confused, the worst that will happen is that I'll tell you that I can't answer that on an exam. 

=== Online Final Exam
You will need to complete an online final exam on the Netacad site.

include::program-info:ROOT:partial$stdfooter.adoc[]