= ITC-2621 Syllabus

Course Name: Cisco Enterprise Advanced Routing and Services (CCNP 2) +
Course Number: ITC-2621-91 +
Instructor: Dr. Ben Franske +
Term: Spring 2024 (1/9/2024-5/7/2024) +
Meetings: Not Required (See details below) +
Location: Online

--
NOTE: In Spring 2024 this course is being offered as a "tutorial" due to the low enrollment in the course. _In a tutorial, faculty meet with students for one-third of the course's student-credit value and students work independently for the remaining two-thirds._ This is a sort of blend between a course and an independent study. As a result there are some changes to how this course is traditionally offered and the amount of instructor availability.
--

== Instructor Contact Information

include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)

* ITC 2536, ITC 2611, or CCNP Enterprise Core Exam

=== Course Description

Explores the implementation and troubleshooting of advanced routing technologies and services. These include: extensive routing protocol troubleshooting, VPN services including DMVPN, infrastructure security troubleshooting, infrastructure services, and infrastructure automation. This course is designed to prepare students for the Implementing Cisco Enterprise Advanced Routing and Services (ENARSI) CCNP exam and is the second in a series of two courses preparing for the CCNP Enterprise certification.

=== Required Resources

* CCNP Enterprise Advanced Routing ENARSI 300-410 Official Cert Guide _2nd Edition_ (Lacoste, Edgeworth) ISBN: 978-0138217525  

+
--
CAUTION: Yes, This textbook really is required. Unlike many Cisco Networking Academy classes there is not a free online version on Netacad!
--

+
--
TIP: Make sure to get the second edition, the first edition printed version of this book has many errors in it. You can also avoid these errors by getting the ebook version _from the publisher_ Cisco Press. Note that Amazon and other ebook versions are not necessarily updated.
--
* CCNP and CCIE Enterprise Core & CCNP Enterprise Advanced Routing Portable Command Guide (Empson, Gargano) ISBN: 978-0135768167

=== Optional Resources


=== Course Website(s)

* ITC Info (https://info.ihitc.net)
* Cisco Networking Academy (http://www.netacad.com)

+
--
WARNING: It is important that you keep an accurate email address on file with the Cisco Networking Academy site and/or regularly sign on to the site to check your Networking Academy Inbox. Important and time-sensitive course information may be distributed through the Networking Academy messaging system. If you have an accurate email address you can receive the information by email as well.
--

== Lab Time

* Packet Tracer can not be used to complete labs in this course
* All labs for this class may be completed remotely using the IHCC Netlab system
* Equipment access, both physical on campus and remote Netlab, is on a first come, first served basis.
* Open on campus lab time may also be available under the supervision of the lab assistant or ITC department instructors, contact the instructor or ITC lab assistant for more information. Students who do not show up for open lab hours they have scheduled may be restricted from registering for open lab hours in the future.

+
--
TIP: If you are struggling with labs it's strongly suggested you make arrangements to come to campus and work on them where you can get more immediate help if you get stuck.
--

== Course Objectives

The student will be able to:

* Troubleshoot administrative distance (all routing protocols)
* Troubleshoot route map for any routing protocol (attributes, tagging, filtering)
* Troubleshoot loop prevention mechanisms (filtering, tagging, split horizon, route poisoning)
* Troubleshoot redistribution between any routing protocols or routing sources
* Troubleshoot manual and auto-summarization with any routing protocol
* Configure and verify policy-based routing
* Configure and verify VRF-Lite
* Describe Bidirectional Forwarding Detection
* Troubleshoot EIGRP (classic and named mode)
* Troubleshoot OSPF (v2/v3)
* Troubleshoot BGP (Internal and External)
* Describe MPLS operations (LSR, LDP, label switching, LSP)
* Describe MPLS Layer 3 VPN
* Configure and verify DMVPN (single hub)
* Troubleshoot device security using IOS AAA (TACACS+, RADIUS, local database)
* Troubleshoot router security features: IPv4 access control lists (standard, extended, time-based), IPv6 traffic filter, Unicast reverse path forwarding (uRPF)
* Troubleshoot control plane policing (CoPP) (Telnet, SSH, HTTP(S), SNMP, EIGRP, OSPF, BGP)
* Describe IPv6 First Hop security features (RA guard, DHCP guard, binding table, ND inspection/snooping, source guard)
* Troubleshoot device management: Console, VTY, Telnet, HTTP, HTTPS, SSH, SCP, (T)FTP
* Troubleshoot SNMP (v2c, v3)
* Troubleshoot network problems using logging (local, syslog, debugs, conditional debugs, timestamps)
* Troubleshoot IPv4 and IPv6 DHCP (DHCP client, IOS DHCP server, DHCP relay, DHCP options)
* Troubleshoot network performance issues using IP SLA (jitter, tracking objects, delay, connectivity)
* Troubleshoot NetFlow (v5, v9, flexible NetFlow)
* Troubleshoot network problems using Cisco DNA Center assurance (connectivity, monitoring, device health, network health)

== Course Design

This course will be taught as a fully online course with your choice of instructor meetings or written progress reports. This means that you will be able to meet with the instructor during a scheduled time each week or turn in a written progress report each week. Additional details about this are available on the assignments page of the course website. 

== Assignments and Grading

Grades will be determined by performance on unit multiple-choice tests, lab exercises, participation, a skills exam, and a final exam. A description of assignments is available from the course website. It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your overall course grade depending on the type of the assignment. 

=== Late Assignments and Extensions

If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor.

If you miss or do poorly on a regular unit/module/chapter exam (not a final exam or skills final exam) you may petition the instructor to retake the exam once. You will need to write a 400-500 word summary of the unit/module/chapter which is covered by the exam. This summary must be written by you personally, the use of any automatic summarization tools or summaries by others will be considered cheating on the exam and is subject to the academic integrity policies covered elsewhere. Your summary must also be written to the satisfaction of the instructor. Retakes or make-ups must be completed by the date specified by the instructor. There is generally no additional late penalty for an exam retake other than needing to write and submit the summary. 

=== Grading Scale

[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability

Grades for this course are calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Unit Assessments 
|20%
|Lab/Homework Assignments 
|35%
|Regular Final Exam 
|15%
|Skills Based Final Exam
|15%
|Participation Activities
|15% 
|===

Detailed information about assignments and which category they are included in is on the "Assignments" page of the course website.

Mid-Term grades are not officially distributed but assignment scores are made available in the online grade book as assignments are graded and you may calculate your current course grade at any time using the above instructions and weighting. It is strongly suggested that if you want to know where you stand in the class you re-create your own copy of the gradebook with appropriate weights in a spreadsheet program such as OpenOffice Calc, Microsoft Excel, or Google Sheets where you can estimate scores you will likely get on future assignments and run other "what-if" scenarios.

CAUTION: Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 

=== Extra Credit

Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Unless otherwise noted extra credit will be added to the Lab/Homework Assignments category. 

=== Special Note on Exam Cheating

It is unacceptable to look for or find copies of exams, exam questions, or scenarios online and use them to complete your exam. Answering a question or scenario incorrectly based on the exam you are taking but in a way that was indicated as correct on a version of the exam which was found online will be seen as evidence of intentional cheating. You will receive a penalty and it will be reported as indicated in the course and campus policies section below.

In plain English... I know some copies of exams for this course circulate online. I look at these and may modify the exam you are given so that a different answer is correct for what looks to be a similar question. You may call these "trick questions" but in this case they are only a trick question if you have seen a stolen copy of an old exam. If you answer one or more of these as shown on the stolen exam this will be evidence of cheating and you will be punished according to cheating policies. Do not cheat, do not look for or use stolen exams.

See the course and campus policies section below for additional information on cheating policies. 

=== Special Note on Lab Cheating

In the case of lab activities which are designed to use physical lab equipment you must work on physical lab equipment, no simulators are allowed. Unless specific permission is given by the instructor this means you must use the IHCC lab equipment on campus or the IHCC Netlab remote lab system. Any evidence that you have turned in a lab report for a lab which is designed to be completed on physical equipment without using physical equipment will be treated as cheating.

See the course and campus policies section below for additional information on cheating policies. 

== Course and Campus Policies

include::ROOT:partial$campus-policies.adoc[]

== Updates to this Syllabus

The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]