= ITC-2621 Syllabus

Course Name: Cisco Enterprise Advanced Routing and Services (CCNP 2) +
Course Number: ITC-2621-91 +
Instructor: Dr. Ben Franske +
Term: Spring 2025 (1/13/2025-5/14/2025) +
Meetings: Tu 6:00-7:30pm +
Location: Online

== Instructor Contact Information

include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)

* ITC 2536, ITC 2611, or CCNP Enterprise Core Exam

=== Course Description

Explores the implementation and troubleshooting of advanced routing technologies and services. These include: extensive routing protocol troubleshooting, VPN services including DMVPN, infrastructure security troubleshooting, infrastructure services, and infrastructure automation. This course is designed to prepare students for the Implementing Cisco Enterprise Advanced Routing and Services (ENARSI) CCNP exam and is the second in a series of two courses preparing for the CCNP Enterprise certification.

=== Required Resources

* CCNP Enterprise Advanced Routing ENARSI 300-410 Official Cert Guide _2nd Edition_ (Lacoste, Edgeworth) ISBN: 978-0138217525  

+
--
CAUTION: Yes, This textbook really is required. Unlike many Cisco Networking Academy classes there is not a free online version on Netacad!
--

+
--
TIP: Make sure to get the second edition, the first edition printed version of this book has many errors in it. You can also avoid these errors by getting the ebook version _from the publisher_ Cisco Press. Note that Amazon and other ebook versions are not necessarily updated.
--
* CCNP and CCIE Enterprise Core & CCNP Enterprise Advanced Routing Portable Command Guide (Empson, Gargano) ISBN: 978-0135768167

=== Optional Resources


=== Course Website(s)

* ITC Info Site for ITC-2621 (https://info.ihitc.net/franske-courses/current/itc-2621/)
* IHCC D2L (https://inverhills.learn.minnstate.edu)
* Cisco Networking Academy (http://www.netacad.com)

+
--
WARNING: It is important that you keep an accurate email address on file with the Cisco Networking Academy site.
--

== Lab Time

* Packet Tracer can not be used to complete labs in this course
* All labs for this class may be completed remotely using the IHCC Netlab system
* Equipment access, both physical on campus and remote Netlab, is on a first come, first served basis.
* Open on campus lab time may also be available under the supervision of the lab assistant or ITC department instructors, contact the instructor or ITC lab assistant for more information. Students who do not show up for open lab hours they have scheduled may be restricted from registering for open lab hours in the future.

+
--
TIP: If you are struggling with labs it's strongly suggested you make arrangements to come to campus and work on them where you can get more immediate help if you get stuck.
--

== Course Objectives

The student will be able to:

* Troubleshoot administrative distance (all routing protocols)
* Troubleshoot route map for any routing protocol (attributes, tagging, filtering)
* Troubleshoot loop prevention mechanisms (filtering, tagging, split horizon, route poisoning)
* Troubleshoot redistribution between any routing protocols or routing sources
* Troubleshoot manual and auto-summarization with any routing protocol
* Configure and verify policy-based routing
* Configure and verify VRF-Lite
* Describe Bidirectional Forwarding Detection
* Troubleshoot EIGRP (classic and named mode)
* Troubleshoot OSPF (v2/v3)
* Troubleshoot BGP (Internal and External)
* Describe MPLS operations (LSR, LDP, label switching, LSP)
* Describe MPLS Layer 3 VPN
* Configure and verify DMVPN (single hub)
* Troubleshoot device security using IOS AAA (TACACS+, RADIUS, local database)
* Troubleshoot router security features: IPv4 access control lists (standard, extended, time-based), IPv6 traffic filter, Unicast reverse path forwarding (uRPF)
* Troubleshoot control plane policing (CoPP) (Telnet, SSH, HTTP(S), SNMP, EIGRP, OSPF, BGP)
* Describe IPv6 First Hop security features (RA guard, DHCP guard, binding table, ND inspection/snooping, source guard)
* Troubleshoot device management: Console, VTY, Telnet, HTTP, HTTPS, SSH, SCP, (T)FTP
* Troubleshoot SNMP (v2c, v3)
* Troubleshoot network problems using logging (local, syslog, debugs, conditional debugs, timestamps)
* Troubleshoot IPv4 and IPv6 DHCP (DHCP client, IOS DHCP server, DHCP relay, DHCP options)
* Troubleshoot network performance issues using IP SLA (jitter, tracking objects, delay, connectivity)
* Troubleshoot NetFlow (v5, v9, flexible NetFlow)
* Troubleshoot network problems using Cisco DNA Center assurance (connectivity, monitoring, device health, network health)

== Course Design

This course will be taught as a fully online course with regular synchronous instructor meetings. This means that you will be meeting regularly with the instructor in an online web conference call during the scheduled course time to assess your progress. Additional details about this are available on the course website. 

== Assignments and Grading

Grades will be determined by performance on unit multiple-choice tests, lab exercises, participation, a skills exam, and a final exam. A list and description of all assignments is linked to from here: https://info.ihitc.net/franske-courses/current/itc-2621/ It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your overall course grade depending on the type of the assignment.

Deadlines and due dates for assignments are listed on the official course schedule linked to here: https://info.ihitc.net/franske-courses/current/itc-2621/

WARNING: It is ultimately your responsibility to ensure that all required assignments as identified on the ITC Info Site course assignments page are completed and submitted by the deadline on the ITC Info Site course schedule page. Do not rely on looking at a gradebook or dates in any online platforms to determine what assignments are due or when, the information on the ITC Info Site always takes precedence over anything else.

=== Late Assignments and Extensions

If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor.

If you miss or do poorly on a regular unit/module/chapter exam (not a final exam or skills final exam) you may petition the instructor to retake the exam once. You will need to write a 400-500 word summary of the unit/module/chapter which is covered by the exam. This summary must be written by you personally, the use of any automatic summarization tools or summaries by others will be considered cheating on the exam and is subject to the academic integrity policies covered elsewhere. Your summary must also be written to the satisfaction of the instructor. Retakes or make-ups must be completed by the date specified by the instructor. There is generally no additional late penalty for an exam retake other than needing to write and submit the summary. 

A last date and time that any late work may be turned in may be included on the course schedule, if so work turned in after that deadline will not be graded and will not be worth any points. If no date is specified late work may be submitted for credit until the end of the last regular class meeting.

=== Grading Scale

[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability

Grades for this course are calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Unit Assessments 
|20%
|Lab/Homework Assignments 
|35%
|Regular Final Exam 
|15%
|Skills Based Final Exam
|15%
|Participation Activities
|15% 
|===

Detailed information about assignments and which grade category they are included in is on the "Assignments" page of the ITC Info course website.

Your grade on most activities can be found in the D2L gradebook for the course; however, exam grades are located on the Cisco Networking Academy website until they are copied into D2L at the end of the semester.

WARNING: The final grade shown in both the Cisco Networking Academy gradebook and the D2L gradebook will be incorrect until all grades are synchronized at the end of the semester and the grading is adjusted to show that missing assignments count as 0 instead of being ignored. You should not trust anything that says final grade to check how you are doing in the course until and unless your instructor explicitly states that final grades are up to date. To find out how you are doing in the course see the next section of the syllabus.

=== Figuring Out How You Are Doing in this Class
A common question of students is "How am I doing in this class?" but it is a very difficult thing for your instructor to answer because students often want different levels of detail and have different expectations about both what kind of information they should get when they ask this question and what it means to be "doing well". Do not wait until near the end of the semester to review your progress in the course. By then both most assignments have already been due for some time and there is little time to make any changes to how you have been doing things.

There are really three approaches to checking your progress in the course:

The first and simplest level is just a quick check-up to see if you've been doing all the work required and if there are any scores that seem wildly out of wack. Your instructor is usually willing to help you assess this as it can be done in just a few minutes. This involves opening any and all of the grade books that are used in the class and reviewing your scores (as well as noting any assingments you have not turned in). Be sure to pay close attention to what category each assignment will end up in when your final grade is calculated. This is a quick way to check on how things are going but won't give you a specific grade you're currently at or a grade you're likely to receive in the class.

If you want a more solid idea of where you are at right now in the course you'll need to spend a bit more time working out your exact current grade in each category. You should not use your total category scores from online gradebooks as they vary quite a bit in how they handle missing assignments (until the end of the semester when they become 0s) amongst other things. Instead, you should put build a spreadsheet with a list of every assignment in a program such as OpenOffice Calc, Microsoft Excel, or Google Sheets.

. Put the assignment name in one column, your score in another column, the total possible points on the assignment in a third column, and the grade category the assignment goes into in a fourth column.
. Sort the list of assignments by the grade category column so that all assignments in each grade category are next to one another.
. Calculate your average percentage on the assignments in each category (add up all the points you earned in the category, and divide by all the points possible in the category)
. Look at your average percentage in each category as well as how important the category is to your final grade (in the above section of the syllabus) and decide if you are happy with your progress so far.

It's still not really possible to give an exact grade to you because there are many things which don't come into play until the very end of the course such as final exams, final skills exams, presentations, etc. So, if you want to go a step further and estimate your final grade what you should do is to keep working with your spreadsheet you started above.
. Add in all assignments which are not graded yet or are not due yet so that the spreadsheet includes all the assignments that will exist on the last day of the class.
. Put in estimates for the earned points based on what you think you will get on each of those assignments
. Calculate your average percentage on the assignments in each category (add up all the points you earned or estimated you will earn in the category, and divide by all the points possible in the category)
. Take the average percentage in each category and multiply it by the weighted percentage for the category (in the above section of the syllabus) and add all of those values together to get your estimated final grade (assuiming the score you get on all remaining assignments is what you estimated).

If you are satisfied with how you are doing both on individual assignments as well as in each category of assignments then you probably don't need to make a change. If you are not satisfied and you know what you need to do to get higher scores that's easy, if you don't know how to improve your scores it is a good idea to ask your instructor about what you could do. Asking the instructor how you can improve your grade at the very end of the semester is not really useful because the answer is there is not much you can usually do after an assignment is due to change the grade and it's annoying to your instructor. For this reason it's always a good idea to monitor your grade throughout the semester and ask your instructor about it as soon as you notice something concerning.

CAUTION: Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 

=== Extra Credit

Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Unless otherwise noted extra credit will be added to the Lab/Homework Assignments category. 

=== Special Note on Exam Cheating

It is unacceptable to look for or find copies of exams, exam questions, or scenarios online and use them to complete your exam. Answering a question or scenario incorrectly based on the exam you are taking but in a way that was indicated as correct on a version of the exam which was found online will be seen as evidence of intentional cheating. You will receive a penalty and it will be reported as indicated in the course and campus policies section below.

In plain English... I know some copies of exams for this course circulate online. I look at these and may modify the exam you are given so that a different answer is correct for what looks to be a similar question. You may call these "trick questions" but in this case they are only a trick question if you have seen a stolen copy of an old exam. If you answer one or more of these as shown on the stolen exam this will be evidence of cheating and you will be punished according to cheating policies. Do not cheat, do not look for or use stolen exams.

See the course and campus policies section below for additional information on cheating policies. 

=== Special Note on Lab Cheating

In the case of lab activities which are designed to use physical lab equipment you must work on physical lab equipment, no simulators are allowed. Unless specific permission is given by the instructor this means you must use the IHCC lab equipment on campus or the IHCC Netlab remote lab system. Any evidence that you have turned in a lab report for a lab which is designed to be completed on physical equipment without using physical equipment will be treated as cheating.

See the course and campus policies section below for additional information on cheating policies. 

== Course and Campus Policies

include::ROOT:partial$campus-policies.adoc[]

== Updates to this Syllabus

The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]