= ITC-2000 Assignment Details and Directions

== Labs
For each topic listed below having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities listed below the topic. Submissions are made through the NetAcad site. You do not need to submit answers to the questions in the activities, those are for your own learning use only. Lab activities may include remote equipment access or campus equipment. *Good lab reports in this class are typically 400-700 words long.* Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

=== PC Disassembly/Reassembly Labs
In this lab activity you will completely disassmble and then re-assemble a small form factor computer. If time allows you may also assemble a computer from parts. 

You should primarily refer to the demonstration disassembly and re-assembly that was done in class but if you need additional reminders of the steps you may refer to the following lab activites in the Cisco Networking Academy curriculum:

* 1.3.2.3 Lab - Disassemble a Computer
* 2.1.2.5 Lab - Install the Power Supply
* 2.1.3.10 Lab - Install the Motherboard in a Computer
* 2.1.4.7 Lab - Install the Drives
* 2.1.5.6 Lab - Install Adapter Cards
* 2.1.7.4 Lab - Install Internal Cables
* 2.1.7.8 Lab - Install the Front Panel Cables
* 2.1.7.11 Lab - Complete the Computer Assembly

=== Boot/BIOS Labs

=== Hardware Troubleshooting Labs

=== Networking Labs

=== Printer Labs

=== Virtualization/Linux Labs

=== Windows Installation Labs

=== Windows Administration Labs

=== Mobile Device Labs

=== Security Labs

=== Support Labs

== Homework
Homework activities will require submitting the actual answers to each question in the activity and may require showing your work as well. Homework assignment are individual, you and your lab partner need to both turn them in separately even if you work on them together.

* Participate in an online forum discussion (typically 3 quality posts or more) of each module on the Cisco Netacad site. See the xref:forum-posting:index.adoc[forum posting page] for details. (up to 10 points each module based on quality)

TIP: Discussion forum posts are usually worth a larger portion of your final grade than most students expect! If you have not done discussion posts in one of Dr. Franske's classes before, or you want to try and score better on discussion forum postings, be sure to check out the xref:forum-posting:index.adoc[instructions for participating in forum discussions and example posts]!

== Participation Activities
Any participation activities completed in the course will go here. This falls into the participation category of your course grade.

* Attend at least two Student Success Day presentations and bring proof of attendance signed by each presenter (10 points)
* Meet with an academic advisor (10 points for meeting)
* Complete a program/degree plan (10 points for completing)
* Complete the online course feedback form (5 points for completing)
* Complete the Practice Final Exam (Chapters 1-9) (10 points for attempting)
* Complete the Practice Final Exam (Chapters 10-14) (10 points for attempting)
* Compete the A+ 220-1101 Certification Practice Exam (10 points for attempting)
* Compete the A+ 220-1102 Certification Practice Exam (10 points for attempting)
* Weekly Progress Self-Evaluation - Complete on the Netacad Website (10 points possible each week)
* Computer History Summary Report (15 points)
** Write a 400-500 word summary of the information you learned in the video and why you think it may be useful to know about that history in your IT career. Submit your report through the Netacad site.

== Unit Assessments
You are responsible for completing all of the online module assessments listed below. These exams fall into the online assessments category of your course grade. 

* Module 1 Exam - Introduction to Personal Computer Hardware
* Module 2 Exam - PC Assembly
* Module 3 Exam - Advanced Computer Hardware
* Module 4 Exam - Preventive Maintenance and Troubleshooting
* Module 5 Exam - Networking Concepts
* Module 6 Exam - Applied Networking
* Module 7 Exam - Laptops and Other Mobile Devices
* Module 8 Exam - Printers
* Module 9 Exam - Virtualization and Cloud Computing
* Module 10 Exam - Windows Installation
* Module 11 Exam - Windows Configuration
* Module 12 Exam - Mobile, Linux, and macOS Operating Systems
* Module 13 Exam - Security
* Module 14 Exam - The IT Professional

== Skills Final Exam
The Skills Final Exam is designed to test your ability to apply the concepts learned in this class and practiced in labs to common, real-world scenarios. There are two parts to this portion of your grade.

* Half of your grade in this category will be based on successfully disassembling and reassembling a computer.
* Half of your grade in this category will be based on successfully installing and configuring the Windows operating system to the specifications provided.

== Online Final Exam
* You will need to complete an online final exam on the Netacad site.

include::program-info:ROOT:partial$stdfooter.adoc[]