= ITC-2000 Syllabus

Course Name: PC Hardware and Software (A+) +
Course Number: ITC-2000-61 +
Instructor: Dr. Ben Franske +
Term: Fall 2024 (8/26/2024-12/19/2024) +
Meetings: Tu Th 10:00-11:50am +
Location: S130

== Instructor Contact Information
include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)
* Placement into ENG 1108 or completion of both ENG 0099 and READ 0093/0094 with a grade of C or higher.

=== Course Description
Presents an in-depth exposure to computer hardware and operating systems. Students learn the functionality of hardware and software components as well as suggested best practices in maintenance and safety issues. Students learn how to assemble and configure a computer, install operating systems and software, and troubleshoot hardware and software problems. This course helps students prepare for CompTIA's A+ certification exam, which covers the knowledge and skills essential for becoming a successful computer technician.

=== Required Resources
* External USB Drive, 8GB minimum, flash drive or hard drive which can be completely erased for use in this class
* Phillips Screwdriver, two sizes, #1 and #2
* Needle Nose Pliers
* Anti-Static Wrist Strap


=== Optional Resources
* IT Essentials: Companion Guide v8 ISBN: 978-0138166106
* A+ Guide to IT Technical Support (Hardware and Software) 11th Edition ISBN: 978-0357674161
* CompTIA A+ Core 1 (220-1101) and Core 2 (220-1102) Exam Cram ISBN: 978-0137637546
* CompTIA A+ Practice Questions Exam Cram Core 1 (220-1101) and Core 2 (220-1102) ISBN: 978-0137658183

=== Additional Information
* Accidental Empires: How the Boys of Silicon Valley Make Their Millions, Battle Foreign Competition, and Still Can't Get a Date (Cringely) ISBN: 978-0887308550
* Revolution in the Valley: The Insanely Great Story of How the Mac Was Made (Hertzfeld) ISBN: 978-0596007195

=== Course Website(s)
* ITC Info (https://info.ihitc.net)
* Cisco Networking Academy (http://www.netacad.com)

+
--
WARNING: It is important that you keep an accurate email address on file with the Cisco Networking Academy site and/or regularly sign on to the site to check your Networking Academy Inbox. Important and time-sensitive course information may be distributed through the Networking Academy messaging system. If you have an accurate email address you can receive the information by email as well.
--

== Lab Time
* Equipment Labs in the PC Hardware and Software course must be completed with physical equipment on campus or at home with your own equipment (requires advance instructor permission).
* Some labs may be completed using the remote Netlab system. These labs must be completed using the Inver Hills Netlab system and should normally be completed in class but may be completed at home with specific instructor permission.
* Equipment access, both physical on campus and remote Netlab, is on a first come, first served basis.
* Additional open on campus lab time may also be available under the supervision of the lab assistant or ITC department instructors, contact the instructor or ITC lab assistant for more information. Students who do not show up for open lab hours they have scheduled may be restricted from registering for open lab hours in the future.  

== Course Objectives
The student will be able to:

* Explain motherboard components, types and features
* Explain the process and steps to install and configure the Windows OS
* Given a scenario, demonstrate proper use of user interfaces
* Given a scenario, demonstrate the appropriate use of communication skills and professionalism in the workplace
* Given a scenario, determine the troubleshooting methods and tools for printers
* Explain the basic principles of security concepts and technologies
* Categorize network cables and connectors and their implementations
* Classify power supplies types and characteristics
* Compare and contrast memory types, characteristics and their purpose
* Compare and contrast the different Windows Operating Systems and their features
* Compare and contrast the different network types
* Distinguish between the different display devices and their characteristics
* Explain cooling methods and devices
* Explain the purpose and characteristics of CPUs and their features
* Given a scenario, explain and interpret common hardware and operating system symptoms and their causes
* Given a scenario, explain and interpret common laptop issues and determine the appropriate basic troubleshooting method
* Given a scenario, explain the troubleshooting theory
* Given a scenario, install, configure and maintain
* Given a scenario, integrate common preventative maintenance techniques
* Install and configure peripherals and input devices
* Install and configure printers
* Install, configure and optimize laptop components and features
* Outline the purpose of appropriate safety and environmental procedures and given a scenario apply them
* Summarize the basics of networking fundamentals, including technologies, devices and protocols
* Summarize the following security features
* Summarize the function and types of adapter cards

== Assignments and Grading
Grades will be determined by performance on unit multiple-choice tests, lab exercises, participation, a skills exam, and a final exam. A description of assignments is available from the course website. It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your overall course grade depending on the type of the assignment.

=== Late Assignments and Extensions
If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor.

If you miss or do poorly on a regular unit/module/chapter exam (not a final exam or skills final exam) you may petition the instructor to retake the exam once. You will need to write a 400-500 word summary of the unit/module/chapter which is covered by the exam. This summary must be written by you personally, the use of any automatic summarization tools or summaries by others will be considered cheating on the exam and is subject to the academic integrity policies covered elsewhere. Your summary must also be written to the satisfaction of the instructor. Retakes or make-ups must be completed by the date specified by the instructor. There is generally no additional late penalty for an exam retake other than needing to write and submit the summary. 

=== Grading Scale
[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability
Grades for each course is calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Module Assessments 
|22%
|Lab/Homework Assignments 
|33%
|Regular Final Exam 
|15%
|Skills Based Final Exam
|15%
|Participation Activities
|15% 
|===

Detailed information about assignments and which category they are included in is on the "Assignments" page of the course website.

Mid-Term grades are not officially distributed but assignment scores are made available in the online grade book as assignments are graded and you may calculate your current course grade at any time using the above instructions and weighting. It is strongly suggested that if you want to know where you stand in the class you re-create your own copy of the gradebook with appropriate weights in a spreadsheet program such as OpenOffice Calc, Microsoft Excel, or Google Sheets where you can estimate scores you will likely get on future assignments and run other "what-if" scenarios.

CAUTION: Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 

=== Extra Credit
Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Unless otherwise noted extra credit will be added to the Lab/Homework Assignments category. 

=== Special Note on Exam Cheating
It is unacceptable to look for or find copies of exams, exam questions, or scenarios online and use them to complete your exam. Answering a question or scenario incorrectly based on the exam you are taking but in a way that was indicated as correct on a version of the exam which was found online will be seen as evidence of intentional cheating. You will receive a penalty and it will be reported as indicated in the course and campus policies section below.

In plain English... I know some copies of exams for this course circulate online. I look at these and may modify the exam you are given so that a different answer is correct for what looks to be a similar question. You may call these "trick questions" but in this case they are only a trick question if you have seen a stolen copy of an old exam. If you answer one or more of these as shown on the stolen exam this will be evidence of cheating and you will be punished according to cheating policies. Do not cheat, do not look for or use stolen exams.

See the course and campus policies section below for additional information on cheating policies. 

=== Special Note on Lab Cheating
In the case of Packet Tracer activities this means you must start with the file provided by your instructor or as part of the curriculum and complete the activity yourself. You may of course ask others for help figuring something out but you must do the work yourself. Do not simply follow tutorials or videos from start to finish showing how to complete the activity as that will not allow you to learn the process and you will likely score poorly on lab exams. You may never ask anyone else to complete an activity for you or turn in an activity completed by someone else, this will be treated as cheating.

In the case of lab activities which are designed to use physical lab equipment you must work on physical lab equipment, no simulators are allowed. Unless specific permission is given by the instructor this means you must use the IHCC lab equipment on campus or the IHCC Netlab remote lab system. Any evidence that you have turned in a lab report for a lab which is designed to be completed on physical equipment without using physical equipment will be treated as cheating.

See the course and campus policies section below for additional information on cheating policies. 

== Course and Campus Policies
include::ROOT:partial$campus-policies.adoc[]

== Updates to this Syllabus
The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]