= ITC-2000 Syllabus

Course Name: PC Hardware and Software (A+) +
Course Number: ITC-2000 +
Instructor: Dr. Ben Franske +
Term: Spring 2025 (1/13/2025-5/14/2025) +
Section 1 Meetings: Tu Th 10:00-11:50am +
Section 2 Meetings: W 6:00-9:50pm +
Location: S130

== Instructor Contact Information
include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)
* Placement into ENG 1108 or completion of both ENG 0099 and READ 0093/0094 with a grade of C or higher.

=== Course Description
Presents an in-depth exposure to computer hardware and operating systems. Students learn the functionality of hardware and software components as well as suggested best practices in maintenance and safety issues. Students learn how to assemble and configure a computer, install operating systems and software, and troubleshoot hardware and software problems. This course helps students prepare for CompTIA's A+ certification exam, which covers the knowledge and skills essential for becoming a successful computer technician.

=== Required Resources
* External USB Drive, 8GB minimum, flash drive or hard drive which can be completely erased for use in this class
* USB to Ethernet Adapter (https://www.amazon.com/dp/B00M77HMU0[such as this $10 one])
* Non-Magnetic Phillips Screwdriver, two sizes, #1 and #2 
* Needle Nose Pliers
* Anti-Static Wrist Strap (https://www.amazon.com/dp/B08CXQN86W[such as this $6 one])


=== Optional Resources
* IT Essentials: Companion Guide v8 ISBN: 978-0138166106
* A+ Guide to IT Technical Support (Hardware and Software) 11th Edition ISBN: 978-0357674161
* CompTIA A+ Core 1 (220-1101) and Core 2 (220-1102) Exam Cram ISBN: 978-0137637546
* CompTIA A+ Practice Questions Exam Cram Core 1 (220-1101) and Core 2 (220-1102) ISBN: 978-0137658183

=== Additional Information
* Accidental Empires: How the Boys of Silicon Valley Make Their Millions, Battle Foreign Competition, and Still Can't Get a Date (Cringely) ISBN: 978-0887308550
* Revolution in the Valley: The Insanely Great Story of How the Mac Was Made (Hertzfeld) ISBN: 978-0596007195

=== Course Website(s)
* ITC Info Site for ITC-2000 (https://info.ihitc.net/franske-courses/current/itc-2000/)
* IHCC D2L (https://inverhills.learn.minnstate.edu)
* Cisco Networking Academy (http://www.netacad.com)

+
--
WARNING: It is important that you keep an accurate email address on file with the Cisco Networking Academy site.
--

== Lab Time
* Equipment Labs in the PC Hardware and Software course must be completed with physical equipment on campus or at home with your own equipment (requires advance instructor permission).
* Some labs may be completed using the remote Netlab system. These labs must be completed using the Inver Hills Netlab system and should normally be completed in class but may be completed at home with specific instructor permission.
* Equipment access, both physical on campus and remote Netlab, is on a first come, first served basis.
* Additional open lab time on campus may also be available under the supervision of the lab assistant or ITC department instructors, contact the instructor or ITC lab assistant for more information. Students who do not show up for open lab hours they have scheduled may be restricted from registering for open lab hours in the future.

== Course Objectives
The student will be able to:

* Explain motherboard components, types and features
* Explain the process and steps to install and configure the Windows OS
* Given a scenario, demonstrate proper use of user interfaces
* Given a scenario, demonstrate the appropriate use of communication skills and professionalism in the workplace
* Given a scenario, determine the troubleshooting methods and tools for printers
* Explain the basic principles of security concepts and technologies
* Categorize network cables and connectors and their implementations
* Classify power supplies types and characteristics
* Compare and contrast memory types, characteristics and their purpose
* Compare and contrast the different Windows Operating Systems and their features
* Compare and contrast the different network types
* Distinguish between the different display devices and their characteristics
* Explain cooling methods and devices
* Explain the purpose and characteristics of CPUs and their features
* Given a scenario, explain and interpret common hardware and operating system symptoms and their causes
* Given a scenario, explain and interpret common laptop issues and determine the appropriate basic troubleshooting method
* Given a scenario, explain the troubleshooting theory
* Given a scenario, install, configure and maintain
* Given a scenario, integrate common preventative maintenance techniques
* Install and configure peripherals and input devices
* Install and configure printers
* Install, configure and optimize laptop components and features
* Outline the purpose of appropriate safety and environmental procedures and given a scenario apply them
* Summarize the basics of networking fundamentals, including technologies, devices and protocols
* Summarize the following security features
* Summarize the function and types of adapter cards

== Assignments and Grading
Grades will be determined by performance on unit multiple-choice tests, lab exercises, participation activities, a skills exam, and a final exam. A list and description of all assignments is linked to from here: https://info.ihitc.net/franske-courses/current/itc-2000/ It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your overall course grade depending on the type of the assignment.

Deadlines and due dates for assignments are listed on the official course schedule linked to here: https://info.ihitc.net/franske-courses/current/itc-2000/

WARNING: It is ultimately your responsibility to ensure that all required assignments as identified on the ITC Info Site course assignments page are completed and submitted by the deadline on the ITC Info Site course schedule page. Do not rely on looking at a gradebook or dates in any online platforms to determine what assignments are due or when, the information on the ITC Info Site always takes precedence over anything else.

=== Late Assignments and Extensions
If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor.

If you miss or do poorly on a regular unit/module/chapter exam (not a final exam or skills final exam) you may petition the instructor to retake the exam once. You will need to write a 400-500 word summary of the unit/module/chapter which is covered by the exam. This summary must be written by you personally, the use of any automatic summarization tools or summaries by others will be considered cheating on the exam and is subject to the academic integrity policies covered elsewhere. Your summary must also be written to the satisfaction of the instructor. Retakes or make-ups must be completed by the date specified by the instructor. There is generally no additional late penalty for an exam retake other than needing to write and submit the summary.

A last date and time that any late work may be turned in may be included on the course schedule, if so work turned in after that deadline will not be graded and will not be worth any points. If no date is specified late work may be submitted for credit until the end of the last regular class meeting.

=== Grading Scale
[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability
Grades for each course is calculated based on a weighted grade system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. You should be sure to understand how weighted grades work as they can make assignments that are not worth many points actually much more important than it may seem at first glance. Final grades are normally rounded to the nearest whole number but the instructor may round up based on student participation and individual improvement.
 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Module Assessments 
|22%
|Lab/Homework Assignments 
|33%
|Regular Final Exam 
|15%
|Skills Based Final Exam
|15%
|Participation Activities
|15% 
|===

Detailed information about assignments and which grade category they are included in is on the "Assignments" page of the ITC Info course website.

Your grade on most activities can be found in the D2L gradebook for the course; however, exam grades are located on the Cisco Networking Academy website until they are copied into D2L at the end of the semester.

WARNING: The final grade shown in both the Cisco Networking Academy gradebook and the D2L gradebook will be incorrect until all grades are synchronized at the end of the semester and the grading is adjusted to show that missing assignments count as 0 instead of being ignored. You should not trust anything that says final grade to check how you are doing in the course until and unless your instructor explicitly states that final grades are up to date. To find out how you are doing in the course see the next section of the syllabus.

=== Figuring Out How You Are Doing in this Class
A common question of students is "How am I doing in this class?" but it is a very difficult thing for your instructor to answer because students often want different levels of detail and have different expectations about both what kind of information they should get when they ask this question and what it means to be "doing well". Do not wait until near the end of the semester to review your progress in the course. By then both most assignments have already been due for some time and there is little time to make any changes to how you have been doing things.

There are really three approaches to checking your progress in the course:

The first and simplest level is just a quick check-up to see if you've been doing all the work required and if there are any scores that seem wildly out of wack. Your instructor is usually willing to help you assess this as it can be done in just a few minutes. This involves opening any and all of the grade books that are used in the class and reviewing your scores (as well as noting any assingments you have not turned in). Be sure to pay close attention to what category each assignment will end up in when your final grade is calculated. This is a quick way to check on how things are going but won't give you a specific grade you're currently at or a grade you're likely to receive in the class.

If you want a more solid idea of where you are at right now in the course you'll need to spend a bit more time working out your exact current grade in each category. You should not use your total category scores from online gradebooks as they vary quite a bit in how they handle missing assignments (until the end of the semester when they become 0s) amongst other things. Instead, you should put build a spreadsheet with a list of every assignment in a program such as OpenOffice Calc, Microsoft Excel, or Google Sheets.

. Put the assignment name in one column, your score in another column, the total possible points on the assignment in a third column, and the grade category the assignment goes into in a fourth column.
. Sort the list of assignments by the grade category column so that all assignments in each grade category are next to one another.
. Calculate your average percentage on the assignments in each category (add up all the points you earned in the category, and divide by all the points possible in the category)
. Look at your average percentage in each category as well as how important the category is to your final grade (in the above section of the syllabus) and decide if you are happy with your progress so far.

It's still not really possible to give an exact grade to you because there are many things which don't come into play until the very end of the course such as final exams, final skills exams, presentations, etc. So, if you want to go a step further and estimate your final grade what you should do is to keep working with your spreadsheet you started above.
. Add in all assignments which are not graded yet or are not due yet so that the spreadsheet includes all the assignments that will exist on the last day of the class.
. Put in estimates for the earned points based on what you think you will get on each of those assignments
. Calculate your average percentage on the assignments in each category (add up all the points you earned or estimated you will earn in the category, and divide by all the points possible in the category)
. Take the average percentage in each category and multiply it by the weighted percentage for the category (in the above section of the syllabus) and add all of those values together to get your estimated final grade (assuiming the score you get on all remaining assignments is what you estimated).

If you are satisfied with how you are doing both on individual assignments as well as in each category of assignments then you probably don't need to make a change. If you are not satisfied and you know what you need to do to get higher scores that's easy, if you don't know how to improve your scores it is a good idea to ask your instructor about what you could do. Asking the instructor how you can improve your grade at the very end of the semester is not really useful because the answer is there is not much you can usually do after an assignment is due to change the grade and it's annoying to your instructor. For this reason it's always a good idea to monitor your grade throughout the semester and ask your instructor about it as soon as you notice something concerning.

CAUTION: Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 

=== Extra Credit
Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Unless otherwise noted extra credit will be added to the Lab/Homework Assignments category. 

=== Special Note on Exam Cheating
It is unacceptable to look for or find copies of exams, exam questions, or scenarios online and use them to complete your exam. Answering a question or scenario incorrectly based on the exam you are taking but in a way that was indicated as correct on a version of the exam which was found online will be seen as evidence of intentional cheating. You will receive a penalty and it will be reported as indicated in the course and campus policies section below.

In plain English... I know some copies of exams for this course circulate online. I look at these and may modify the exam you are given so that a different answer is correct for what looks to be a similar question. You may call these "trick questions" but in this case they are only a trick question if you have seen a stolen copy of an old exam. If you answer one or more of these as shown on the stolen exam this will be evidence of cheating and you will be punished according to cheating policies. Do not cheat, do not look for or use stolen exams.

See the course and campus policies section below for additional information on cheating policies. 

=== Special Note on Lab Cheating
In the case of Packet Tracer activities this means you must start with the file provided by your instructor or as part of the curriculum and complete the activity yourself. You may of course ask others for help figuring something out but you must do the work yourself. Do not simply follow tutorials or videos from start to finish showing how to complete the activity as that will not allow you to learn the process and you will likely score poorly on lab exams. You may never ask anyone else to complete an activity for you or turn in an activity completed by someone else, this will be treated as cheating.

In the case of lab activities which are designed to use physical lab equipment you must work on physical lab equipment, no simulators are allowed. Unless specific permission is given by the instructor this means you must use the IHCC lab equipment on campus or the IHCC Netlab remote lab system. Any evidence that you have turned in a lab report for a lab which is designed to be completed on physical equipment without using physical equipment will be treated as cheating.

See the course and campus policies section below for additional information on cheating policies. 

== Course and Campus Policies
include::ROOT:partial$campus-policies.adoc[]

== Updates to this Syllabus
The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]