= ITC-2900 Official Course Schedule

== Jan 16
* 6:00-8:30pm Required Course Kickoff Meeting on Campus in S132
* Form Teams
* Choose Projects & Get Approval
* Begin Project Research

== Jan 23
* First Draft Statement of Work due! Submit via D2L by 11:59pm

== Jan 30
* Final Version Statement of Work due! Submit via D2L by 11:59pm
* You can still make changes to the schedule and scope of your project with the agreement of your instructor as the course goes on but your SoW needs to be finalized and submitted now.

== Apr 14
* Have your YouTube video presentation completed, uploaded and available
* YouTube Presentation link must be submitted by one group member on D2L before 11:59pm

== May 2
* 1:30-2:30pm - Final Presentation Practice/Setup on Campus
* 2:45-5:00pm - Final Presentations on Campus

== May 7
* Whitepaper due! One group member submit electronically on D2L before 11:59pm -- Hard copies not required for Spring 2021 or 2022
* All group meeting minutes due in a single file! One group member must submit on D2L before 11:59pm
* One group member must submit electronic copy of final presentation on D2L before 11:59pm

== May 9
* Peer evaluations due, submit on D2L
* Individual time logs (spreadsheet) and work journals (narrative document) due, submit on D2L

include::program-info:ROOT:partial$stdfooter.adoc[]