= ITC-2530 Syllabus

Course Name: Enterprise Networking, Security, and Automation (CCNA 3) +
Course Number: ITC-2530 +
Instructor: Dr. Ben Franske +
Term: Spring 2026 (1/12/2026-5/13/2026) +
Meetings: Independent Study +
Location: Independent Study

== Instructor Contact Information
include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)
* ITC 2516 or (ITC 2510 AND ITC 2520)

=== Course Description
Explores the design, management, configuration, and troubleshooting of enterprise computer networks. This includes the ability to configure a dynamic routing protocol, access control lists, and NAT, as well as an understanding of wide area networking, VPNs, quality of service, network security, virtualization, and automation technologies. Enterprise Networking, Security, and Automation is the final in a sequence of three courses focusing on preparation for the Cisco Certified Network Associate (CCNA) certification.

=== Required Resources
* CCNA Routing and Switching Portable Command Guide (5th Edition) (Empson) ISBN: 978013593782-2
* External USB Drive, 8GB free minimum, flash drive or hard drive
* USB to Serial Converter (https://www.amazon.com/dp/B00IDSM6BW[such as this $10 one])
* USB to *Mini* (not micro) USB cable (https://www.amazon.com/dp/B0B3J6RD34[such as this $4 one])
* USB to Ethernet Adater (https://www.amazon.com/dp/B00M77HMU0[such as this $9 one])

=== Optional Resources
* Enterprise Networking, Security, and Automation Companion Guide (CCNAv7) ISBN: 978-0136634324
* Enterprise Networking, Security, and Automation Course Booklet (CCNAv7) ISBN: 978-0136634737
* Enterprise Networking, Security, and Automation Labs & Study Guide (CCNAv7) ISBN: 978-0136634690

=== Course Website(s)
* ITC Info (https://info.ihitc.net)
* Cisco Networking Academy (http://www.netacad.com)
* IHCC D2L Site (https://inverhills.learn.minnstate.edu/d2l/home)

+
--
WARNING: It is important that you keep an accurate email address on file with the Cisco Networking Academy site and/or regularly sign on to the site to check your Networking Academy Inbox. Important and time-sensitive course information may be distributed through the Networking Academy messaging system. If you have an accurate email address you can receive the information by email as well.
--

== Lab Time
* Equipment Labs in this class may be completed with the IHCC Netlab remote access equipment, with physical equipment on campus, or at home with your own equipment (requires advance instructor permission).
* Equipment access, both physical on campus and remote Netlab, is on a first come, first served basis.
* Packet Tracer Labs may be completed on campus or at home and submitted through the ScoreUP system.
* On campus lab time may be available under the supervision of the lab assistant or other ITC department instructors, contact your instructor or ITC lab assistant for more information. Students who do not show up for open lab hours they have scheduled may be restricted from registering for open lab hours in the future.  

== Course Objectives
The student will be able to:

. Explain how single-area OSPF operates in both point-to-point and broadcast multiaccess networks.
. Implement single-area OSPFv2 in both point-to-point and broadcast multiaccess networks.
. Explain how vulnerabilities, threats, and exploits can be mitigated to enhance network security.
. Explain how ACLs are used as part of a network security policy.
. Implement IPv4 ACLs to filter traffic and secure administrative access.
. Implement NAT services on the edge router to provide IPv4 address scalability.
. Explain how WAN access technologies can be used to satisfy business requirements.
. Explain how VPNs and IPsec are used to secure site-to-site and remote access connectivity.
. Explain how networking devices implement QoS.
. Implement network management protocols to monitor the network.
. Explain the characteristics of scalable network architectures.
. Troubleshoot enterprise networks using the layered model, a systematic process, and appropriate tools.
. Explain the purpose and characteristics of network virtualization.
. Explain how network automation is enabled through RESTful APIs and configuration management
tools.

== Course Design
This course will be taught as an independent study course. This means that you are primarily responsible for your own learning in the course. Reading and multimedia materials for this course will be made available through the Cisco Networking Academy website. The instructor will be available to assist you if you are stuck on labs/activities and to answer specific questions you have and provide general guidance for the course. Recorded lectures are available as well. There will be great flexibility in most due dates but this will require extra attention and planning as a student in the class as you will be mostly responsible for ensuring the required work is completed on your own. There are periodic required milestone dates which are indicated on the xref:sp26schedule.adoc[Spring 2026 Official Course Schedule].

It is strongly recommended that you review the xref:schedule.adoc["regular semester" schedule for the class] and try to stick fairly close to it in terms of when readings/lectures and lab work is completed to ensure you will complete everything before the few milestone dates. You will also be more on your own to assess your understanding and progress in the class than in a typical course. If you have any questions about content, labs, and other work in the course it will be your responsibility to bring those questions and concerns up to the instructor.

Even though unit exams, discussion postings, and points for weekly check-ins will not be required during this independet study you are strongly encouraged to do these things (or substantially equivalent activtities) anyway as they are designed to help with your understanding of the content and to prepare you for final exams and skills exams.

== Assignments and Grading
Grades will be determined by performance on lab exercises, a skills exam, and a final exam. A description of assignments is available from the course website. It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your overall course grade depending on the type of the assignment.

=== Late Assignments and Extensions
If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor.

Some assignments cannot be turned in late. These assignments are indicated as such on the ITC Info site course assignments page. If one of these must be turned in late because of written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor an alternative assignment may be given instead.

All late work must be turned in no later than May 1, 2026 no late work will be accepted after that date.

=== Grading Scale
[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability

Grades for the course are calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Lab/Homework Assignments 
|60%
|Regular Final Exams (one for CCNA 3 and one for Cybersecurity Essentials)
|20%
|Skills Based Final Exams (two for CCNA 1 and two for CCNA 2)
|20%
|===

Detailed information about assignments and which category they are included in is on the "Assignments" page of the course website.

Mid-Term grades are not officially distributed but assignment scores are made available in the online grade book as assignments are graded and you may calculate your current course grade at any time using the above instructions and weighting. It is strongly suggested that if you want to know where you stand in the class you re-create your own copy of the gradebook with appropriate weights in a spreadsheet program such as OpenOffice Calc, Microsoft Excel, or Google Sheets where you can estimate scores you will likely get on future assignments and run other "what-if" scenarios.

CAUTION: Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 

=== Extra Credit
Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Unless otherwise noted extra credit will be added to the Lab/Homework Assignments category. 

=== Special Note on Exam Cheating
It is unacceptable to look for or find copies of exams, exam questions, or scenarios online and use them to complete your exam. Answering a question or scenario incorrectly based on the exam you are taking but in a way that was indicated as correct on a version of the exam which was found online will be seen as evidence of intentional cheating. You will receive a penalty and it will be reported as indicated in the course and campus policies section below.

In plain English... I know some copies of exams for this course circulate online. I look at these and may modify the exam you are given so that a different answer is correct for what looks to be a similar question. You may call these "trick questions" but in this case they are only a trick question if you have seen a stolen copy of an old exam. If you answer one or more of these as shown on the stolen exam this will be evidence of cheating and you will be punished according to cheating policies. Do not cheat, do not look for or use stolen exams.

See the course and campus policies section below for additional information on cheating policies. 

=== Special Note on Lab Cheating
In the case of Packet Tracer activities this means you must start with the file provided by your instructor or as part of the curriculum and complete the activity yourself. You may of course ask others for help figuring something out but you must do the work yourself. Do not simply follow tutorials or videos from start to finish showing how to complete the activity as that will not allow you to learn the process and you will likely score poorly on lab exams. You may never ask anyone else to complete an activity for you or turn in an activity completed by someone else, this will be treated as cheating.

In the case of lab activities which are designed to use physical lab equipment you must work on physical lab equipment, no simulators are allowed. Unless specific permission is given by the instructor this means you must use the IHCC lab equipment on campus or the IHCC Netlab remote lab system. Any evidence that you have turned in a lab report for a lab which is designed to be completed on physical equipment without using physical equipment will be treated as cheating.

See the course and campus policies section below for additional information on cheating policies. 

== Course and Campus Policies
include::ROOT:partial$campus-policies.adoc[]

== Updates to this Syllabus
The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]