= Degrees and Certificates

Like most IT departments Inver Hills Community College divides offerings related to computers into two broad areas (though there is some crossover), information technology infrastructure and computer science or programming. There are two degrees and six certificates in the information technology infrastructure area and two degrees in the programming area. Networking, Internet access, server administration, hardware, operating systems, and PCs tend to fall in the information technology infrastructure area. Writing software, apps, sofware design, and algorithms tend to fall into the computer science/programming area.

Before making a decision on what specific certificate or degree you want to pursue you'll want to figure out whether the broad area of IT Infrastructure or Computer Science is more interesting to you.

== Information Technology Infrastructure

Information Technology Infrastructure, commonly called IT, is the collection of careers which deal with selecting, installing, integrating, protecting, and maintaining the software and hardware which enables society, business, and the Internet as we know it. This field focuses primarily on the integration of multiple existing hardware and software systyems into a single cohesive design solution to complex problems.

xref:degrees-certificates-it.adoc[Find out about information technology infrastructure certificates and degrees here]

=== Key Skills

* Select and combine multiple technologies to solve problems
* Defend systems and networks from cyber-attacks
* Build, upgrade, and repair computers and other hardware
* Help others by quickly solving their critical technology needs
* Design, setup, and maintain the systems that run the Internet
* Work with powerful networks, servers, firewalls, and more

=== Example Jobs

* Computer Network Architect
* Computer Support Specialist
* Computer Systems Analyst
* Network and Computer System Administrators
* Computer and Information Systems Manager
* Information Security Analyst

== Computer Science and Programming

Computer Science is the study of computers and the algorithmic processes used by them and their software including the theory, principles, design, and applications. This field focuses primarily on the development of new software and algorithms to solve problems.

xref:degrees-certificates-cs.adoc[Find out about computer science and programming certificates and degrees here]

=== Key Skills

* Design and implement the algorithms in software to solve complex social and business problems
* Write, test, and debug the code that powers the modern world from video games, to interactive websites, mobile apps, and business applications
* Express your creativity and unlock the solutions to complex logic problems
* Program in advanced languages such as C++, Java, HTML, JavaScript, Python, and PHP

=== Example Jobs

* Computer Programmer
* Database Administrator
* Software Application Developer
* Software Engineer
* Mobile App Developer
* Web Developer
* Computer Scientist

include::program-info:ROOT:partial$stdfooter.adoc[]