= Degree Course Sequencing
Your specific course sequence may vary depending on whether you start in a Fall or Spring semester and whether you are taking day or evening track classes. These sample sequences are designed to provide a starting point and an example of how you would be able to complete the program in the minimum number of semesters. They are also used to determine which semesters various classes will be available on the schedule (though classes may also be offered other times, these set the minimum semester which classes will be offered). For example classes listed in semesters 1 & 3 of the latest sequence document should be available in the Fall semester and classes listed in semesters 2 & 4 should be available in the Spring semester.

* You can find a copy of the *2022-2023* suggested course sequence document https://docs.google.com/spreadsheets/d/1l6k-eI-VvacEd5jYXVXAcq5luzbwZliJPR5sUan-mr0/edit?usp=sharing[here on Google Sheets]. Note the tabs at the bottom of the document for different degree programs.

* You can find a copy of the *2020-2022* suggested course sequence document https://docs.google.com/spreadsheets/d/16v3zvQcucQk9yx2aszRsKzaFgQK1YaNIHnCTSjmk_Eo/edit?usp=sharing[here on Google Sheets]. Note the tabs at the bottom of the document for different degree programs.

* You can find a copy of the *2019-2020* suggested course sequence document https://docs.google.com/spreadsheets/d/1jrpqR2mpDOwvSEgah6lQUaSu3hwlLAqxLjBzESFY_Qw/edit?usp=sharing[here on Google Sheets]. Note the tabs at the bottom of the document for different degree programs.

* You can find a copy of the *2016-2017* suggested course sequence document https://docs.google.com/spreadsheets/d/1KDM4zaAMYWV_0ccs7-cSkYQUzrYm2AkNRvF7gMb4qmQ/edit?usp=sharing[here on Google Sheets]. Note the tabs at the bottom of the document for different degree programs.

* You can find a copy of the *2015-2016* suggested course sequence document https://docs.google.com/spreadsheets/d/1k6ru7Bh5BjzEQ1pqeVMoy-8ArZtwVOlDLLiDFk-MBPI/edit?usp=sharing[here on Google Sheets]. Note the tabs at the bottom of the document for different degree programs.

=Assumptions=
In determining the course sequence (and the schedule for our classes) we need to make some assumptions. It's OK if you don't match these assumptions but it will likely mean that you will need more than 4 semesters (2 years) to complete your degree. This depends on your specific situation. In any case we do not recommend taking any class before you have completed all of the prerequisites for the class. IT courses build on one another so you should finish any required prerequisite course listed before taking a class.

* *We assume you start in the Fall semester.* We do have some class options if you start in the Spring but you will likely have to wait for some classes too because we just don't have enough students starting in the Spring to run a second copy of every course and, as noted above, IT courses tend to build on one another. If you start in the Spring it's most likely that you will have some lighter semesters (fewer credits) but will probably take an extra semester to graduate.
* *We assume you are a full-time student.* This means you will be taking between 14-16 credits a semester. This is some pretty simple math, to do a 60 credit degree program (as most 2 year degrees are) you need to do an average of 60/4 = 15 credits per semester. Because there is a 4 credit writing class one semester will need to be 16 credits. If you are a full-time student we recommend you do not plan on working more than a few hours a week. Our courses cover a lot of material and we expect that if you are taking 15 credits of classes you are spending about 45 hours a week on classes/homework. That doesn't leave a lot of time for outside employment. Many of our students do work while taking classes but if you are working an appreciable number of hours you should probably plan on being a part-time student and taking fewer classes per semester. These course sequences don't show you exactly which classes to take when in that case, but can provide some useful suggestions about the general order you should take classes in and what semesters certain classes are offered.
* *We assume you do not need to re-take any classes.* Depending on what class it is this could throw you off the track of pre-requisites and that would mean one or two additional semesters before you can get the class you need to continue on your track so graduation will take one or two semesters longer.
* *We assume you do not need to take remedial classes.* If you are not yet ready for any of the classes on the sequence (e.g. you have not placed in to ENG 1108, or haven't tested out of ITC-1200 and want to do the Network Technology & Security degree) that would be additional time beyond the sequence of classes we have laid out as those classes are not really part of the degree itself.

