= Discussion Forum Examples - First Posts

== Example 1 
This example post comes from an early chapter in the CCNA Security course. You can see that both the most important and most interesting parts of the chapter were clearly discusses as well as what the author thinks is the reason they are interesting and important. Questions related to the content of the chapter have been included making it easier for other students to respond to the posting.

=== Post
*Most Important:* It seemed like the most important topic covered by this chapter was an overview of security threats in section 1.2 (i.e. threat vectors, virus/trojan/worm/malware, hackers), the types of hackers (black/grey/white hat, hacktivists, state-sponsored), the types of tools they employ (password crackers, packet sniffers/crafters, rootkits to name a few), and the categories of attacks (eavesdropping, spoofing, DoS, man-in-the-middle, reconnaissance, etc) to give us an idea of how important security is in today's networks and ways to potentially mitigate against those threats (as covered in section 1.3).

*Most Interesting:* One interesting part of the chapter to me was the discussion of 'honeypot' servers and how Norse Dark Intelligence purposefully deploys these decoy servers and study how hackers attempt to breach their security. Afterward, they provide the information to organizations for examination allowing them to come up with countermeasures against it. Similarly, Cisco provides information and mitigation techniques against current attacks on their Cisco Security Intelligence Operations (SIO) site for network administrators.

Another interesting part of the chapter to me was just how secure Data Center Networks are. Because of the amounts of sensitive business data they house, they are not only securely interconnected to corporate sites (e.g. via VPN/ASA devices) but also require many levels of physical security; Some examples include security officers, fences/gates, video surveillance, alarms, motion detectors, traps, and bio-metric access/exit (such as a badge ID to enter the trap and then facial/fingerprint recognition to enter and exit the data hall).


*Questions:* How do they make a 'honeypot' server an attractive enough target for hackers? Do they leave certain vulnerabilities open on purpose, make them conspicuous enough, or are networks so routinely under attack that none of these measures are necessary?

Also, when a virtual machine hosted on cloud computing that has outdated security (hasn't been powered on in a long time for example) connects to the internet, would that be considered a threat vector to the rest of the network (like hyperjacking) or is the sand-boxed nature of virtual machines enough of a preventive measure?

== Example 2  
This post comes from an early chapter in the PC Hardware & Software class. It clearly describes what the author thought the most important and interesting parts of the chapter where and why as well as a couple of questions related to the content of the chapter.

=== Post
I personally thought the most important concept from chapter one was the compatibility of components. For example processors manufactured by AMD have a physically different design to those manufactured by Intel. So, If a technician is building a computer, they must select a CPU that is compatible with the motherboard they have chosen. This is important because incompatibility can cause a computer to fail, even if all the components are operational.

I thought the most interesting section of the chapter was the one about the differing ports and cables. Before this reading I was only familiar with the most common types of ports/cables like DVI, HDMI, USB, etc. I had heard the name of some of the other types of ports/cables, but I did not know what they were used for or how they compared to each other. I now understand each type of port/cable, and its function.

I was wondering generally how long it took for new technologies to be adopted by the public. Also, why has USB persisted if thunderbolt has been so much faster for much longer?

include::program-info:ROOT:partial$stdfooter.adoc[]