=== Attendance
After the first class meeting formal attendance will not be taken; however, students are expected to arrive to class on time and participate in class. Students are expected to attend all sessions of each class in which they are enrolled. If attendance is a problem participation assignments may be given and included in the course grade. If an illness or emergency results in an absence, students should contact their instructors as soon as possible to determine if missed work can be completed. A student may receive a course grade of FN or NC after two consecutive weeks of unexcused absence at any time during the semester. Class attendance is defined as being physically present in the classroom. Online attendance is defined as having submitted an assignment, taken a quiz, or posted/made a course content-related comment on the discussion/chat board for the course in which the student is registered.  

=== Use and Access to Technology
You will need daily access to a high-speed internet connection (DSL, cable modem, 4G, fiber, or equivalent) and a modern computer to successfully complete this course. 

=== Academic Integrity (Plagiarism and Cheating)
Academic integrity is one of the most important values in higher education. This principle requires that each student's work represents his or her own personal efforts and that the student acknowledges the intellectual contributions of others. The foundation for this principle is student academic honesty. IHCC students are expected to honor the requirements of the College Academic Integrity Policy. The following are some examples of unacceptable academic practices that will be viewed as policy violations.

For the purposes of this policy artificial intelligence (AI) systems such as ChatGPT or automatic summarization systems are "another person". As such they are prohibted unless authorized in advance by your instructor.

It is unacceptable to submit the work of another person as your own. If you quote, summarize, paraphrase, or use the ideas of another, you must accurately attribute that information. If you do not acknowledge the source, you are plagiarizing. Academic dishonesty also includes unauthorized collaboration on academic work; taking, acquiring, or using test materials without faculty permission; submitting the same assignment for multiple classes without instructor permission; taking an examination for another person and many other situations. If you are unsure whether you are plagiarizing or how to cite a source please ask an instructor or staff member for help prior to turning in the assignment.

In this course, the first offense of plagiarism and/or cheating will result in a score of zero on the assignment, quiz or test and reporting of the incident to college administration. Further plagiarism and/or cheating may result in immediate failure of the course and additional consequences determined by college administration.

If you have cheated in other ITC courses that will count as your first offense. In other words, if you have cheated in ITC courses before cheating in this course may result in immediately failing the course and additional consequences determined by college administration.

All instances of cheating will be reported to the college administration. In addition, plagiarism and cheating are covered by the Student Code of Conduct. Please see the Catalog or IHCC website for details. 

=== Withdrawing from the Course
Students must initiate requests for withdrawal from a course by filing the appropriate form with Enrollment Services. Students who stop attending classes without completing the withdrawal process may receive a grade of “F,” and are responsible for all tuition/fees associated with the course registration. The last day to withdraw from your course will be the date on which 80% of the course has elapsed. The last day to withdraw for each course can be viewed in E-Services by searching for the course at the following link: https://webproc.mnscu.edu/registration/search/basic.html?campusid=157. Click on the course title to view additional details about the course, including last day to withdraw. 

There are limits as to the latest date you can withdraw from the course and still receive a refund as well as the last date to withdraw from the course at all. Please see the Add, Drop and Withdraw page on the IHCC website: https://inverhills.edu/Registration/AddDropWithdraw.aspx

=== E-mail Communications
Recognizing the value and efficiency of communication between faculty/staff and students through electronic mail Inver Hills Community College has designated e-mail as an official mode of communication. At the same time, email raises some issues concerning security and the identity of each individual in an email exchange. Therefore, students are asked to regularly check and utilize the email address they have registered with the college. If your email address has changed it is your responsibility to make sure the college has an up-to date email address where you can be contacted. You should check your email on a regular basis as course changes and communications may be sent by email. 

=== Pass/Fail Grade Option
A student may elect to take a course on a pass/fail (P/F) grading basis by contacting the instructor within the first 5 business days of the semester, or within 1 business day of the start date for a course beginning after the first week of the semester. If the instructor approves, they will submit approval to the Enrollment Center. Not all courses are approved for students to elect the P/F grading method and there may be limits to the total number of classes which can be taken pass/fail in your degree or certificate program. Contact your instructor for details about what level of achievement in the course will be required to receive a pass in the course. 

=== Access and Accommodations
Inver Hills values diversity and inclusion; we are committed to fostering mutual respect and full participation for all students. My goal is to create a learning environment that is equitable, inclusive and welcoming. If any aspects of instruction or course design result in barriers to your inclusion or learning, please notify me. The Office of Accessibility Resources (OAR) provides reasonable accommodations and assistive technologies for students who encounter barriers in the learning environment. Services are available to students with a wide range of disabilities including, but not limited to, physical disabilities, medical conditions, learning disabilities, attention deficit disorder, depression, and anxiety. If you have already registered with OAR and have your Letter of Accommodation, please meet with me early in the course to discuss, plan, and implement your accommodations in the course. For additional information, please contact OAR located within the Learning Center (L207), 651-450-3884, accessibilityresources@inverhills.edu or https://www.inverhills.edu/LearningSupport/AccessibilityResources/index.aspx

=== Religious Accommodation Statement
In accordance with federal and state laws, Inver Hills Community College is committed to a policy of free expression and respect for the diversity of beliefs, including religious observances, among our academic community. It is the policy of the college to provide reasonable accommodations for students when religious beliefs and/or observances conflict with classroom activities or course requirements.

It is the responsibility of students to notify instructors of the need for accommodation at the beginning of the course or as soon as a situation arises. If a mutually agreed accommodation is not made, a student may initiate a complaint. The procedure for filing a complaint is described in the Catalog and on the Inver Hills website. The complaint must be filed within 15 days of a denied accommodation request.