= ITC-2611 Assignment Details and Directions

== Lab & Homework Assignments

=== Lab Reports
For each chapter having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities listed below in the chapter. Submissions are made through the NetAcad site. You do not need to submit answers to the questions in the activities, those are for your own learning use only. Lab activities may include remote equipment access or campus equipment. *Good lab reports in this class are typically 400-700 words long.* Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

[NOTE] 
.When Using Netlab Remote Lab System
==== 
* The login password for CAASP Pod PCs in Netlab is: Cisco123
====

. Lab 1.1.2 - Implement Inter-VLAN Routing
. Lab 2.1.2 - Observe STP Topology Changes and Implement RSTP
. Lab 3.1.2 - Implement Advanced STP Modifications and Mechanisms
. Lab 4.1.2 - Implement MST
. Lab 5.1.2 - Implement VTP
. Lab 5.1.3 - Implement EtherChannel
. Lab 5.1.4 - Tuning EtherChannel
. Lab 6.1.2 - Investigate Static Routes
. Lab 6.1.3 - Implement VRF-Lite
. Lab 8.1.2 - Implement Single-Area OSPFv2
. Lab 9.1.2 - Implement Mult-Area OSPFv2
. Lab 9.1.3 - OSPFv2 Route Summarization and Filtering
. Lab 10.1.2 - Implement Multiarea OSPFv3
. Lab 11.1.2 - Implement eBGP for IPv4
. Lab 11.1.3 - Implement MP-BGP
. Lab 12.1.2 - Implement BGP Path Manipulation
. Lab 12.1.3 - Implement BGP Communities
. Lab 15.1.2 - Implement NTP
. Lab 15.1.3 - Implement HSRP
. Lab 15.1.4 - Implement VRRP
+
--
TIP: If you have a problem activating VRRP on a switch it's possible the IP Services license is not active. You can go ahead and activate if needed.
--
. Lab 15.1.5 - Implement GLBP
. Lab 15.1.6 - Implement NAT
. Lab 16.1.2 - Implement a GRE Tunnel
. Lab 16.1.3 - Implement IPsec Site-to-Site
+
--
TIP: If you have a problem configuring IPSec on a router it's possible the Security license is not active. You can go ahead and activate if needed.
--
. Lab 16.1.4 - Implement GRE over IPsec Site-to-Site VPNs
. Lab 16.1.5 - Implement IPsec VTI Site-to-Site VPNs
. Lab 24.1.2 - Use Connectivity Tests and Debug for Network Assurance
. Lab 24.1.3 - Implement SNMP and Syslog
. Lab 24.1.4 - Implement Flexible Netflow
. Lab 24.1.5 - Implement SPAN Technologies
. Lab 24.1.6 - Implement IP SLA
. Lab 25.1.2 - Install the CCNP Virtual Machine
+
--
NOTE: You can find the CCNP Virtual Machine OVA file in the CCNP folder on the desktop of each PC in the Pod. Be sure to randomize the MAC address when you import the OVA file.
--
. Lab 26.1.2 - Implement IPv4 ACLs
. Lab 26.1.3 - Configure Protections for Passwords and Terminal Lines
. Lab 26.1.4 - Configure Local and Server-Based AAA Authentication
+
--
NOTE: You will be using the CCNP VM in Virtual Box on your Pod PC. Be sure the MAC address of the VM is different on each Pod PC if you run the VM on more than one PC.
--
. Lab 26.1.6 - Implement CoPP
. Lab 28.1.2 - Construct a Basic Python Script
. Lab 28.1.3 - Use the Netmiko Python Module to Configure a Router
. Lab 28.1.4 - Use NETCONF To Access an IOS XE Device
. Lab 28.1.5 - Use RESTCONF to Access an IOS XE Device

=== Homework

* Participate in an online forum discussion (typically 3 quality posts or more) of each chapter on the Cisco Netacad site. See the xref:forum-posting:index.adoc[forum posting page] for details. (up to 10 points each chapter based on quality)

TIP: Discussion forum posts are usually worth a larger portion of your final grade than most students expect! If you have not done discussion posts in one of Dr. Franske's classes before, or you want to try and score better on discussion forum postings, be sure to check out the xref:forum-posting:index.adoc[instructions for participating in forum discussions and example posts]!

== Participation Activities
Any participation activities completed in the course will go here. This falls into the participation category of your course grade.

* Complete the online course feedback form (5 points for completing)
* Complete the online certification practice exam (10 points for attempting)
* Meet with the instructor once per week to discuss course progress and ask questions (up to 10 points each based on progress)

== Unit Assessments
You are responsible for completing all of the online unit assessments listed below. Multiple chapters are included in single exams. These exams fall into the online assessments category of your course grade. 

* Chapters 1 - 5: L2 Redundancy Exam
* Chapters 6 - 7: Routing Essentials and EIGRP Exam
* Chapters 8 - 10: OSPF Exam
* Chapters 11 - 12: BGP Exam
* Chapters 13 - 14: Multicast and QoS Exam
* Chapters 15 - 16: IP Services and VPNs Exam
* Chapters 17 - 19: Wireless Essentials Exam
* Chapters 20 - 21: Wireless Security and Connectivity Exam
* Chapters 22 - 24: Network Design and Monitoring Exam
* Chapters 25 - 26: Access Control and Infrastructure Security Exam
* Chapters 27 - 29: Virtualization, Automation, and Programmability Exam

== Skills Final Exam
The Skills Final Exam is designed to test your ability to apply the concepts learned in this class and practiced in labs to common, real-world scenarios. Your grade in this category will be based on completing a lab equipment skills exam. You will not be able to use any resources other than those specified by your instructor on this part of the exam. 

== Online Final Exam
You will need to complete an online final exam on the Netacad site.

include::program-info:ROOT:partial$stdfooter.adoc[]