= ITC-2611 Syllabus
Course Name: Cisco Enterprise Network Core Technologies (CCNP 1) +
Course Number: ITC-2611-91 +
Instructor: Dr. Ben Franske +
Term: Fall 2022 (8/22/2022-12/15/2022) +
Meetings: Tu 6:00-8:30pm +
Location: Online

== Instructor Contact Information
include::ROOT:partial$instructor-contact.adoc[]

== General Course Information
=== Prerequisite(s)
* ITC 2535, ITC 2530, or CCNA Certification 

=== Course Description
Explores the core technologies of an enterprise network. Focuses on implementing core enterprise network technologies including dual stack (IPv4 and IPv6) architecture, virtualization, layer 2, 3, and wireless infrastructure, network assurance, security and automation. This is the first of two courses preparing students for the Cisco Certified Network Professional Enterprise certification. 

=== Required Resources
* Official Cert Guide: CCNP and CCIE Enterprise Core ENCOR 350-401 (Edgeworth, Garza Rios, Gooley, Hucaby) ISBN: 978-1587145230 
CAUTION: Yes, This textbook really is required. Unlike many Cisco Networking Academy classes there is not a free online version on Netacad!
TIP: The first edition printed version of this book has many errors in it. You can avoid these errors by getting the ebook version _from the publisher_ Cisco Press. Note that Amazon and other ebook versions are not necessarily updated.
* CCNP and CCIE Enterprise Core & CCNP Enterprise Advanced Routing Portable Command Guide (Empson, Gargano) ISBN: 978-0135768167

=== Optional Resources


=== Course Website(s)
* ITC Info (https://info.ihitc.net)
* Cisco Networking Academy (http://www.netacad.com)
+
--
WARNING: It is important that you keep an accurate email address on file with the Cisco Networking Academy site and/or regularly sign on to the site to check your Networking Academy Inbox. Important and time-sensitive course information may be distributed through the Networking Academy messaging system. If you have an accurate email address you can receive the information by email as well.
--

== Lab Time
* Packet Tracer can not be used to complete labs in this course
* All labs for this class may be completed remotely using the Netlab system
* Equipment access, both physical on campus and remote Netlab, is on a first come, first served basis.
* Open on campus lab time may also be available under the supervision of the lab assistant or ITC department instructors, contact the instructor or ITC lab assistant for more information. Students who do not show up for open lab hours they have scheduled may be restricted from registering for open lab hours in the future.
+
--
TIP: If you are struggling with labs it's strongly suggested you make arrangements to come to campus and work on them where you can get more immediate help if you get stuck.
--

== Course Objectives
The student will be able to:

* Explain the different design principles used in an enterprise network
* Analyze design principles of a WLAN deployment
* Differentiate between on-premises and cloud infrastructure deployments
* Explain the working principles of the Cisco SD-WAN solution
* Explain the working principles of the Cisco SD-Access solution
* Describe concepts of wired and wireless QoS
* Differentiate hardware and software switching mechanisms
* Describe device virtualization technologies
* Configure and verify data path virtualization technologies
* Describe network virtualization concepts
* Troubleshoot static and dynamic 802.1q trunking protocols
* Troubleshoot static and dynamic EtherChannels
* Configure and verify common Spanning Tree Protocols (RSTP and MST)
* Compare routing concepts of EIGRP and OSPF (advanced distance vector vs. linked state, load balancing, path selection, path operations, metrics)
* Configure and verify simple OSPF environments, including multiple normal areas, summarization, and filtering (neighbor adjacency, point-to-point and broadcast network types, and passive interface)
* Configure and verify eBGP between directly connected neighbors (best path selection algorithm and neighbor relationships)
* Describe Layer 1 wireless concepts, such as RF power, RSSI, SNR, interference noise, band and channels, and wireless client devices capabilities
* Describe AP modes and antenna types
* Describe access point discovery and join process (discovery algorithms, WLC selection process)
* Describe the main principles and use cases for Layer 2 and Layer 3 roaming
* Troubleshoot WLAN configuration and wireless client connectivity issues
* Describe Network Time Protocol (NTP) 
* Configure and verify NAT/PAT
* Configure first hop redundancy protocols, such as HSRP and VRRP
* Describe multicast protocols, such as PIM and IGMP v2/v3
* Diagnose network problems using tools such as debugs, conditional debugs, trace route,ping, SNMP, and syslog
* Configure and verify device monitoring using syslog for remote logging
* Configure and verify NetFlow and Flexible NetFlow
* Configure and verify SPAN/RSPAN/ERSPAN
* Configure and verify IPSLA
* Describe Cisco DNA Center workflows to apply network configuration, monitoring, and management
* Configure and verify NETCONF and RESTCONF
* Configure and verify device access control
* Configure and verify infrastructure security features
* Describe REST API security
* Configure and verify wireless security features
* Describe the components of network security design
* Interpret basic Python components and scripts
* Construct valid JSON encoded file
* Describe the high-level principles and benefits of a data modeling language, such as YANG
* Describe APIs for Cisco DNA Center and vManage
* Interpret REST API response codes and results in payload using Cisco DNA Center and RESTCONF
* Construct EEM applet to automate configuration, troubleshooting, or data collection
* Compare agent vs. agentless orchestration tools, such as Chef, Puppet, Ansible, and SaltStack

== Course Design
This course will be taught as a fully online course with regular synchronous instructor meetings. This means that you will be meeting regularly with the instructor in an online web conference call during the scheduled course time to assess your progress. Additional details about this are available on the course website. 

== Assignments and Grading
Grades will be determined by performance on unit multiple-choice tests, lab exercises, participation, a skills exam, and a final exam. A description of assignments is available from the course website. It is expected that assignments will be completed and turned in on time and as specified.

Failure to turn in one or more assignments without approval from the instructor may result in an additional lack of participation penalty of up to 20% of your overall course grade depending on the type of the assignment. 

=== Late Assignments and Extensions
If assignments are turned in late 10% will be deducted for each day or partial day the assignment is late. *If you are turning in an assignment late you must contact the instructor for information before the due date. Failure to do so may result in additional penalties.* The grading of late assignments is given a lower priority and may take longer so students are encouraged to plan ahead and turn in assignments on time. Penalty-free deadline extensions will not be given without written documentation from a licensed medical practitioner or other extenuating circumstances at the discretion of the instructor.

If you miss or do poorly on a regular unit/module/chapter exam (not a final exam or skills final exam) you may petition the instructor to retake the exam once. You will need to write a 400-500 word summary of the unit/module/chapter which is covered by the exam. This summary must be written by you personally, the use of any automatic summarization tools or summaries by others will be considered cheating on the exam and is subject to the academic integrity policies covered elsewhere. Your summary must also be written to the satisfaction of the instructor. Retakes or make-ups must be completed by the date specified by the instructor. There is generally no additional late penalty for an exam retake other than needing to write and submit the summary. 

=== Grading Scale
[%autowidth,options="header"]
|===
|Letter Grade |Percentage Range |Description
|A
|100%-90%
|achievement that is outstanding relative to the level necessary to meet course requirements
|B
|89%-80%
|achievement that is significantly above the level necessary to meet course requirements
|C
|79%-70%
|achievement that meets the course requirements in every respect
|D
|69%-65%
|achievement that is worthy of credit even though it fails to meet fully the course requirements
|F
|64%-0%
|Represents failure and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|N
|
|Represents no credit and signifies that the work was either (1) completed but at a level of achievement that is not worthy of credit or (2) was not completed and there was no agreement between the instructor and the student that the student would be awarded an I (see also I)
|I
|
|Represents incomplete and is assigned at the discretion of the instructor when, due to extraordinary circumstances, e.g., hospitalization, a student is prevented from completing the work of the course on time. Requires a written agreement between instructor and student. Students must request an incomplete from the instructor.
|===

=== Grading Method and Availability
This course is a combination of two Cisco Networking Academy courses, CCNA 1 and CCNA 2. Grades for each of these two courses will be calculated separately following the method below and then the two courses will be averaged for a final grade in the single 6 credit college course.

Grades for each course is calculated based on a weighted points system. Each assignment, quiz or test is assigned to one of the weighted categories below and is graded on a points system. Your percentage is calculated for each category by dividing the points earned in that category by the points available. Finally, your percentage earned in each category is multiplied by the weight of that category and these are added together. The instructor may round up based on student participation and individual improvement. 
 
[%autowidth,options="header"]
|===
|Category |Percent of Final Grade
|Unit Assessments 
|20%
|Lab/Homework Assignments 
|35%
|Regular Final Exam 
|15%
|Skills Based Final Exam
|15%
|Participation Activities
|15% 
|===

Detailed information about assignments and which category they are included in is on the "Assignments" page of the course website.

Mid-Term grades are not officially distributed but assignment scores are made available in the online grade book as assignments are graded and you may calculate your current course grade at any time using the above instructions and weighting. It is strongly suggested that if you want to know where you stand in the class you re-create your own copy of the gradebook with appropriate weights in a spreadsheet program such as OpenOffice Calc, Microsoft Excel, or Google Sheets where you can estimate scores you will likely get on future assignments and run other "what-if" scenarios.

CAUTION: Be aware that the final grade in online gradebooks may be calculated in a way which ignores any assignments you have not turned in. At the end of the semester assignments which have not been turned in will have scores of 0 recorded in the gradebook. If you have missing assignments this may cause your grade to suddenly drop from what was previously shown. It is your responsibility to know what assignments you have not completed, that those will become 0s if not turned in, and how that will affect your grade. 

=== Extra Credit
Students should not rely on extra credit to boost their grade and should instead complete each assignment to the best of their ability. However, from time to time extra credit opportunities may arise at which time they will be announced in class, by email and/or through the course website. Unless otherwise noted extra credit will be added to the Lab/Homework Assignments category. 

=== Special Note on Exam Cheating
It is unacceptable to look for or find copies of exams, exam questions, or scenarios online and use them to complete your exam. Answering a question or scenario incorrectly based on the exam you are taking but in a way that was indicated as correct on a version of the exam which was found online will be seen as evidence of intentional cheating. You will receive a penalty and it will be reported as indicated in the course and campus policies section below.

In plain English... I know some copies of exams for this course circulate online. I look at these and may modify the exam you are given so that a different answer is correct for what looks to be a similar question. You may call these "trick questions" but in this case they are only a trick question if you have seen a stolen copy of an old exam. If you answer one or more of these as shown on the stolen exam this will be evidence of cheating and you will be punished according to cheating policies. Do not cheat, do not look for or use stolen exams.

See the course and campus policies section below for additional information on cheating policies. 

=== Special Note on Lab Cheating
In the case of lab activities which are designed to use physical lab equipment you must work on physical lab equipment, no simulators are allowed. Unless specific permission is given by the instructor this means you must use the IHCC lab equipment on campus or the IHCC Netlab remote lab system. Any evidence that you have turned in a lab report for a lab which is designed to be completed on physical equipment without using physical equipment will be treated as cheating.

See the course and campus policies section below for additional information on cheating policies. 

== Course and Campus Policies
include::ROOT:partial$campus-policies.adoc[]

== Updates to this Syllabus
The instructor reserves the right to modify and adjust this syllabus as needed during the course of this class. The most up to date version will always be available on the course website or from the instructor. 

include::program-info:ROOT:partial$stdfooter.adoc[]