= Franske Lab Report Format

== The Basics
In this class credit for completing labs will be based on turning in a written lab report. If labs in this class are done in groups you should turn in a single lab report for each lab completed. If labs are individual you will need to turn in your own lab report which is unique to you. Lab reports should be typed and should include the following information:

* Lab group members (only names on the report for a lab will receive credit for it, also do not list someone who did not actually work on the lab that is cheating)
* Course and section number
* Lab number and title
* A detailed description of what you did for the lab in your own words
* A detailed description of any problems or difficulties you encountered with the lab as well as how you solved them
* A description of how you tested your lab and what the results were
* A description of what new material or skills you learned in this lab

See detailed information about some of these sections below.

Please be as detailed as possible. Remember, points will be awarded based on the information on this report. The less information included the fewer opportunities for the instructor to award points. Lab reports serve multiple purposes including getting you to think critically about what you've just done (metacognition) as well as to provide evidence that you were able to successfully complete the lab. Showing that you are thinking critically about the lab is a good way to score highly on lab reports. If there is evidence that you did not actually complete the lab yourself you may receive a zero on the lab report even if the submitted report is well written.

== The Concept
Instead of asking you to complete questions found in lab books you will create a narrative report on the lab in much the same format you might do in a science or other lab-based course. The advantages of this format is that you will do better quality lab work, get a better understanding of the lab concepts, and have an opportunity to practice valuable technical writing soft-skills.

== The Format
We have developed a lab report format which focuses on four key areas for reflection. These areas are: a description of what you did, what difficulties you had and how you overcame those difficulties, a description of how you tested the lab and a look back on what you learned from the lab. Significant thought was given to selecting these as the key areas for the reports and below are some thoughts about the what the intended purpose and outcome of each area is.

=== What you did/What was the purpose
The purpose of this section is to engage you in a metacognitive exercise thinking about what they did in this particular lab. Particularly in the case of highly prescriptive, step-oriented, labs students often will go through them following the directions but have no idea at the end about what they just did at a broader level and why it is an important thing to learn. In this section we’re looking for a description of the lab in your own words. At a higher level of evaluation we’re looking for evidence that you are aware of how this lab fits into the content of the course as a whole and into the IT field. In the grading of lab reports we often give less emphasis to this area as it’s intended more to force you to think about what they have done. We want you to think about that but we already know what you did, or at least what you were supposed to do so it’s less important from a grading perspective.

=== What difficulties you faced/How you overcame them
The purpose of this section is to assist us in determining what the “hard parts” of the lab were for you and to confirm that you were able to work through them or that you need additional reinforcement on these concepts. An added benefit here is that you need to think though what your troubleshooting process was and ideally what additional efficiencies might be gained or what worked well in that process. This is a critical area from a grading perspective. We can gain significant insight into how the lab worked out for you and what the learning process was for you by reading this section.

=== How you tested your lab
Particularly in labs which are less step-by-step in nature you may often think “are we done with this lab?”. This section requires students think about what it means to have been successful in completing the lab. Just as in the workplace students need to know when they can move on to another project or if there is more to do. We want to get you used to checking to make sure things are working as they expect after doing any system configuration or making a change as well as look to see that you did successfully complete the lab activity. In a similar way to the first section we want to force you to go though the process of thinking about testing the lab but it’s not critical from a grading perspective so we generally weight this section somewhat less than the others.

You should be extremely thorough in this section. Every new concept or command that is introduced in the lab should be thoroughly tested and the testing documented in the report. Many times the lab instructions themselves do '''not''' thoroughly test the technologies used in the lab. Part of doing the lab is to come up with a testing plan ''yourself'' and to document and carry out that testing. It is absolutely unacceptable to simply say that testing of the lab was done by following the instructions. This does not show you know anything about what is supposed to work at all.

=== What you learned
This is a high value section of the lab report. Fundamentally the purpose of labs is to teach you new skills and to have you practice those skills. This section forces you to think about what you got, or should have gotten, out of doing the lab exercise. Sometimes you may have a difficult time understanding why we do lab exercises and you don’t immediately see the value in doing them. Here the goal is to have you try and come up with a narrative about what new things you learned or what was reinforced by the exercise, which is of course the purpose of having you do it. Hopefully we can see evidence that it was a worthwhile activity for you and that you truly did engage in the learning process. Undoubtedly this is the most critical section for grading purposes. Just as you want to know that they accomplished something worthwhile we are fundamentally interested in knowing that you had a positive learning outcome as well.

== Example Lab Reports
Below are some example lab reports posted by students. These are certainly not perfect lab reports but are meant to give you a starting point about what a lab report might look like. You should look at many of these, not just ones for your class, so that you have a good idea of what sort of thing is expected in your reports.

* xref:example1.adoc[Lab Report Example - PC Hardware and Software Class]
* xref:example2.adoc[Lab Report Example - Linux Class]
* xref:example3.adoc[Lab Report Example - Network Security Class]
* xref:example4.adoc[Lab Report Example - CCNA 3 Class]
* xref:example5.adoc[Lab Report Example - CCNP Class]

include::program-info:ROOT:partial$stdfooter.adoc[]