= ITC-2300 Assignment Details and Directions

== Labs
For each module having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities listed below in the module. Submissions are made through the NetAcad site. You do not need to submit answers to the questions in the activities, those are for your own learning use only. Lab activities may include remote equipment access, campus equipment, or packet tracer activities. If you work with a partner on a lab you only need to submit a single lab report for the two of you but it must have both your names on it. Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

=== Virtualization Labs

==== Proxmox VE Installation Lab
Find instructions for the xref:lab-proxmox-installation.adoc[Proxmox VE Installation Lab here].

==== Proxmox VE Containers and Cluster Lab
Find instructions for the xref:lab-proxmox-containersclusters.adoc[Proxmox VE Containers and Cluster Lab here].

==== vmWare ESXi Installation Lab
Find instructions for the xref:lab-vmware-esxiinstallation.adoc[vmWare ESXi Installation Lab here].

==== vmWare vSphere vCenter Server Installation Lab
Find instructions for the xref:lab-vmware-vcenterinstallation.adoc[vmWare vSphere vCenter Server Installation Lab here]].

==== vmWare vSphere Administration Lab
Find instructions for the xref:lab-vmware-vsphereadmin.adoc[vmWare vSphere Administration Lab here]].

=== Network Programmability Labs

==== Getting Started with DevNet Lab

* Complete https://developer.cisco.com/learning/modules/dev-setup[DevNet Developer Workstation and Environment Setup Lab]
+
--
NOTE: In this lab activity you will, amongst other things download and install the OpenConnect VPN client which is used to connect to the DevNet sandbox labs. Unfortunately there is a bug in this software which prevents OpenVPN (which you may use for connecting to ITCnet in other classes) from resetting Windows DNS server addresses. This will prevent you from accessing ITCnet resources, even after disconnecting from the DevNet sandbox VPN in OpenConnect. To fix this after EACH time you use OpenConnect to access DevNet sandboxes after disconnecting you will need to open your network adapter properties for the "TAP-Windows Adapter" and open the IPv4 settings. You will see that OpenConnect has left DNS set as "Use the following DNS server addresses" with two addresses filled in. Change the setting back to "Obtain DNS server address automatically" and save the settings. The next time you connect to OpenVPN you should have access to the ITCnet DNS server and resources again.
--
* Complete the Programming Fundamentals Module from the [https://developer.cisco.com/learning/tracks/devnet-beginner DevNet Beginner] track
+
--
NOTE: In Step 2 of the "A Brief Introduction to Git" lab you are told you should have already downloaded a Git repository or you should follow the link at the top with instructions for setting up your workstation. Follow that link and see the section titled *Using Git to Copy Code and Setting Up the Local Environment*. You should clone and use the Data Center Infrastructure: https://github.com/CiscoDevNet/dciv2-code repository.
--

==== REST API Fundamentals & Network Programmability Lab

* Complete the REST API Fundamentals Module from the https://developer.cisco.com/learning/tracks/devnet-beginner[DevNet Beginner] track
* Complete the Network Programmability Module from the https://developer.cisco.com/learning/tracks/devnet-beginner[DevNet Beginner] track
+
--
NOTE: On page 2 of the "Cisco DNA Center Platform - Authentication" lab and in some future labs you may receive an error about SSL certificates when running code. Because the Cisco DNAC has a self-signed certificate you will need to change Python Requests function calls from things like: <code>requests.post(url, auth=HTTPBasicAuth(DNAC_USER, DNAC_PASSWORD))</code> to things like <code>requests.post(url, auth=HTTPBasicAuth(DNAC_USER, DNAC_PASSWORD), verify=False)</code> by setting the verify flag to false you can tell the Python requests library to ignore SSL certificate verification.
--
NOTE: In the "End to End Visibility and Assurance with Path Trace and Cisco DNA Center Platform" lab you should re-check the "How To Setup Your Own Computer" link at the top of the page. There is a new GitHub repo to clone which contains the path_trace.py file. Also, we don't expect you to be able to write the entire path_trace.py program by yourself at this point. Instead, you should reference that file while reading through the lab's explanation of some of the functions so you can see (and hopefully understand) how the program works and what sorts of information are being pulled from the API when you execute the program. You can also try using Postman to make the same API requests and get the same data that you're getting though Python.
--
NOTE: If you want to see what the GUI interface for Cisco DNA Center looks like you can go to https://sandboxdnac2.cisco.com and sign in with the username devnet and password Cisco123!
--

==== Model Driven Network Programmability and IOS XE Lab

* Complete all modules in the https://developer.cisco.com/learning/tracks/iosxe-programmability[IOS XE Programmability] track
+
--
NOTE: The SSH instructions in the "Exploring IOS XE YANG Data Models with NETCONF" lab are designed for use on an *NIX based system so they will work best with a Linux computer/VM, a Mac, or in the Windows Subsystem for Linux (WSL).
--

==== Getting Started with Ansible for Network Programmability Lab

* Complete all modules in the https://developer.cisco.com/learning/modules/sdx-ansible-intro[Introduction to Ansible] track
* Complete the "Introduction to Configuration Management" and "Introduction to Ansible" modules in the https://developer.cisco.com/learning/modules/intro-ansible-iosxe[Introduction to Ansible for IOS XE Configuration Management] track
* Complete the https://developer.cisco.com/learning/modules/industrial-netdevops/iot-industrial-netdevops-ansible/step/1["Managing IoT Harware with Ansible" module].

== Homework

== Participation Activities

== Unit Assessments

== Other

== Course Project

== Archived Labs

include::program-info:ROOT:partial$stdfooter.adoc[]