= ITC-2300 Assignment Details and Directions

== Labs
For each module having lab activities you will need to submit one xref:lab-reports:index.adoc[lab report] which covers all of the lab activities listed below in the module. Submissions are made through the NetAcad site. Lab activities may include remote equipment access or campus equipment. *Good lab reports in this class are typically 400-700 words long.* If you work with a partner on a lab you only need to submit a single lab report for the two of you but it must have both your names on it. Each lab report is worth up to 20 points.

TIP: If you have not done lab reports in one of Dr. Franske's classes before, or you want to try and score better on lab reports, be sure to check out the xref:lab-reports:index.adoc[instructions for writing lab reports page and example reports]!

=== Virtualization Labs

==== Proxmox VE Installation Lab
Find instructions for the xref:lab-proxmox-installation.adoc[Proxmox VE Installation Lab here].

==== Proxmox VE Containers and Cluster Lab
Find instructions for the xref:lab-proxmox-containersclusters.adoc[Proxmox VE Containers and Cluster Lab here].

==== vmWare ESXi Installation Lab
Find instructions for the xref:lab-vmware-esxiinstallation.adoc[vmWare ESXi Installation Lab here].

==== vmWare vSphere vCenter Server Installation Lab
Find instructions for the xref:lab-vmware-vcenterinstallation.adoc[vmWare vSphere vCenter Server Installation Lab here].

==== vmWare vSphere Administration Lab
Find instructions for the xref:lab-vmware-vsphereadmin.adoc[vmWare vSphere Administration Lab here].

=== Network Programmability Labs

==== Getting Started with DevNet Lab

* Complete https://developer.cisco.com/learning/modules/dev-setup[DevNet Developer Workstation and Environment Setup Lab]
+
--
NOTE: In this lab activity you will, amongst other things download and install the OpenConnect VPN client which is used to connect to the DevNet sandbox labs. Unfortunately there is a bug in this software which prevents OpenVPN (which you may use for connecting to ITCnet in other classes) from resetting Windows DNS server addresses. This will prevent you from accessing ITCnet resources, even after disconnecting from the DevNet sandbox VPN in OpenConnect. To fix this after EACH time you use OpenConnect to access DevNet sandboxes after disconnecting you will need to open your network adapter properties for the "TAP-Windows Adapter" and open the IPv4 settings. You will see that OpenConnect has left DNS set as "Use the following DNS server addresses" with two addresses filled in. Change the setting back to "Obtain DNS server address automatically" and save the settings. The next time you connect to OpenVPN you should have access to the ITCnet DNS server and resources again.
--
* Complete the https://developer.cisco.com/learning/tracks/Coding-APIs-v0/Coding-APIs-Fundamentals-v0/[Coding & APIs - Fundamentals Module]

==== REST API Fundamentals & Network Programmability Lab

* Complete the https://developer.cisco.com/learning/tracks/Coding-APIs-v0/Coding-APIs-TIF-v0/[Coding & APIs Taking It Further Module]
* Complete the https://developer.cisco.com/learning/tracks/netprog-eng/dnac-rest-apis/[Cisco DNA Center REST APIs Module] from the Network Programmability for Network Engineers track
+
--
NOTE: If you want to see what the GUI interface for Cisco DNA Center looks like you can go to https://sandboxdnac2.cisco.com and sign in with the username devnetuser and password Cisco123!
--

==== Model Driven Network Programmability and IOS XR Lab

* Complete the https://developer.cisco.com/learning/tracks/netprog-eng/intro-device-level-interfaces/[Introduction to Model Driven Programmability Module] from the Network Programmability for Network Engineers track
* Complete the https://developer.cisco.com/learning/labs/intro-restconf/introduction/[Exploring IOS XE YANG Data Models with RESTCONF Module]


==== Getting Started with Ansible for Network Programmability Lab

* Complete the https://developer.cisco.com/learning/tracks/programming-dna/intro-ansible-iosxe/[Introduction to Ansible for IOS XE Configuration Management Module]
+
[NOTE]
====
You will see some references to dCloud in these labs. We do not have access to dCloud but can still work with an IOS XE device using the DevNet Sandbox reservation system.

. Make a reservation for the "IOS XE on Cat 8kv Latest Code" sandbox on the https://devnetsandbox.cisco.com/RM/Topology[DevNet Sandbox Site] note that it will take a few minutes for your reservation to setup and you will need access to your email to obtain the VPN credentials which will be emailed to you. 
. Get the Server domain name, VPN Username, and VPN password from the email Cisco will send you when your reservation is ready. Use the `export` commands as described in the lab instructions to connect to the VPN from the shell in your browser. You do NOT need to install the AnyConnect/OpenConnect client on your computer for this lab as you will be using the terminal in your browser which already has it installed.
. When you setup your `hosts` inventory file change the `ansible_user` to the username from the DevNet Sandbox webpage in the "Catalyst 8000v Credentials and Information" section (it is probably `developer`)
. When you setup your `hosts` inventory file you will only have one IP address in the `[iosxe]` section instead of two and the IP address will be the Host address in the "Catalyst 8000v Credentials and Information" section of the DevNet Sandbox webpage (it is probably `10.10.20.48`)
. Note that you can connect to your sandbox router over SSH if you connect to the VPN from your computer with OpenConnect/AnyConnect. After connecting to the VPN use PuTTY/SSH and the credentials and IP address on the sandbox website. This can be useful to see if the changes you make actually apply on the router.

Otherwise follow the lab as normal and you should get output using the developer terminal in your browser as expected (though only on one router instead of two).
====
* Complete the https://developer.cisco.com/learning/tracks/IOT-Edge-v0/IOT-Edge-TIF-v0/iot-industrial-netdevops-ansible/overview/[Getting Started with Ansible on Cisco IoT Hardware lab] in the IOT & Edge Computing-Taking it Further module.
+
--
NOTE: Just do the "Managing IoT Hardware with Ansible: Getting Started" lab from this module
--
+
[IMPORTANT]
====
If you are running the OpenConnect GUI on Windows please start by reviewing https://intercom.help/privatevpn/en/articles/6366468-openconnect-setup-guide-for-windows[these instructions for installing OpenConnect and creating a new OpenConncect profile].

. The gateway will be the _Lab Network Address_ in the email Cisco sends you once your sandbox is ready, but you will have to put `https://` in front of it like `\https://devnetsandbox-usw1-reservation.cisco.com:20215`
. Before you connect you will need to click the gear (options) dropdown and select _Edit selected profile_
.. The _Interface Name_ box should be blank right now. Change it to be `devnetsandbox` and save the changes. The default is based on the gateway address and the gateway addresses used by DevNet are not valid interface names because they are too long.
. You should now be able to connect to the VPN using the username and password in the email Cisco sends you once your sandbox is ready.
====
+
[NOTE]
====
This lab mentions that a sandbox reservation is optional but you will need to create one unless you own your own IOS XE device. Use the Sandbox lab indicated below and not the "IOS XE on CSR Latest Code" one they mention in the lab whihc no longer exists.

. Make a reservation for the "IOS XE on Cat 8kv Latest Code" sandbox on the https://devnetsandbox.cisco.com/RM/Topology[DevNet Sandbox Site] note that it will take a few minutes for your reservation to setup and you will need access to your email to obtain the VPN credentials which will be emailed to you. You WILL need to install the AnyConnect/OpenConnect client on your computer for this lab as you will be connecting from your computer directly to the sandbox.
. On several pages in the lab there is a "On Devbox" set of instructions followed by a "On your Compuer or Laptop" section. These are supposed to be one *OR* the other not both. It will be much easier for you if you follow the "On Devbox" instuctions and skip over the "On your Computer or Laptop" sections as you will not need to install nearly as much stuff on your computer.
. The Developer Box Linux system you will be using has it's IP (probably `10.10.20.50`) and login credentials (probably user `developer` and password `C1sco12345`) documented on the DevNet Sandbox environment page.
. You will need to update the IP address of your router (IOS XRv 9K) in the Ansible hosts file too. Make sure to use the actual IP address of your router as shown on the DevNet Sandbox environment page (it is probably `10.10.20.35`).
. Note that you can connect to your sandbox router and Linux Developer box over SSH as long as you are connected via VPN using the credentials and IP address on the sandbox website. This can be useful to see if the changes you make actually apply on the router.
====
+
--
NOTE: There is an error on the "Ansible hands-on: Show Commands" page of this lab. The first command to execute a playbook is given as `ansible-playbook playbook-simple-ping.yml` but Ansible is not aware of the password to your router. There is a note in the "Explanation" section below this command about the -k argument and the correct command (though with a wrong playbook filename) is shown in the "Expected Output" section below that which is `ansible-playbook playbook-simple-ping.yml -k` When this is entered you should be prompted for the router password (see the DevNet Sandbox page) when you run the playbook.
--

=== Cloud Computing Labs
==== Introduction to the Cloud
* https://azure.microsoft.com/en-us/free/students/[Sign up for an Azure Student Account]
* https://learn.microsoft.com/en-us/training/modules/describe-core-architectural-components-of-azure/4-exercise-explore-learn-sandbox?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.azure-fundamentals-describe-azure-architecture-services[Explore the Learn Sandbox]
* https://learn.microsoft.com/en-us/training/modules/describe-core-architectural-components-of-azure/7-exercise-create-azure-resource?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.azure-fundamentals-describe-azure-architecture-services[Create an Azure resource]
* https://learn.microsoft.com/en-us/training/modules/describe-azure-compute-networking-services/3-exercise-create-azure-virtual-machine?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.azure-fundamentals-describe-azure-architecture-services[Create an Azure virtual machine]
* https://learn.microsoft.com/en-us/training/modules/describe-azure-compute-networking-services/9-exercise-configure-network-access?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.azure-fundamentals-describe-azure-architecture-services[Configure network access]
* https://learn.microsoft.com/en-us/training/modules/describe-azure-storage-services/5-exercise-create-storage-blob?ns-enrollment-type=learningpath&ns-enrollment-id=learn.wwl.azure-fundamentals-describe-azure-architecture-services[Create a storage blob]
* https://learn.microsoft.com/en-us/training/modules/tour-azure-portal/4-exercise-work-with-blades[Work with resources]
* https://learn.microsoft.com/en-us/training/modules/tour-azure-portal/5-exercise-navigate-the-portal[Use the Azure portal]
* https://learn.microsoft.com/en-us/training/modules/tour-azure-portal/7-exercise-customize-the-dashboard[Customize the dashboard]

==== Using Azure Virtual Machines
* https://learn.microsoft.com/en-us/training/modules/intro-to-azure-virtual-machines/3-create-a-vm[Create a VM using the Azure portal]
* https://learn.microsoft.com/en-us/training/modules/create-windows-virtual-machine-in-azure/3-exercise-create-a-vm[Create a Windows virtual machine]
* https://learn.microsoft.com/en-us/training/modules/create-windows-virtual-machine-in-azure/5-exercise-connect-to-a-windows-vm-using-rdp[Connect to a Windows virtual machine using RDP]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/2-create-a-vm[https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/2-create-a-vm]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/3-testing-the-vm[Test your new virtual machine]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/4-other-vm-images[Explore other VM images]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/5-sizing-vms[Sizing VMs properly]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/6-querying-vms[Query system and runtime information about the VM]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/7-managing-vms[Start and stop your VM with the Azure CLI]
* https://learn.microsoft.com/en-us/training/modules/manage-virtual-machines-with-azure-cli/8-installing-software[Install software on your VM]


==== Scaling Azure Virtual Machines
* https://learn.microsoft.com/en-us/training/modules/keep-your-virtual-machines-updated/3-exercise-use-update-management-on-a-virtual-machine[Use Update Management on a virtual machine]
* https://learn.microsoft.com/en-us/training/modules/keep-your-virtual-machines-updated/5-exercise-use-azure-log-analytics-and-schedule-updates[Use Azure log analytics and schedule updates]
* https://learn.microsoft.com/en-us/training/modules/configure-network-for-azure-virtual-machines/3-exercise-create-azure-virtual-network[Create an Azure virtual network]
* https://learn.microsoft.com/en-us/training/modules/configure-network-for-azure-virtual-machines/5-exercise-create-azure-vpn-gateway[Create an Azure VPN gateway]
* https://learn.microsoft.com/en-us/training/modules/create-azure-resource-manager-template-vs-code/3-exercise-create-and-deploy-template?pivots=powershell[Create and deploy an Azure Resource Manager template]
* https://learn.microsoft.com/en-us/training/modules/create-azure-resource-manager-template-vs-code/5-exercise-parameters-output?pivots=powershell[Add parameters and outputs to your Azure Resource Manager template]
* https://learn.microsoft.com/en-us/training/modules/add-and-size-disks-in-azure-virtual-machines/3-exercise-add-data-disks-to-azure-virtual-machines[Add a data disk to a VM]
* https://learn.microsoft.com/en-us/training/modules/add-and-size-disks-in-azure-virtual-machines/6-exercise-resize-disks[Resize a VM disk]

== Homework
Homework activities will require submitting the actual answers to each question in the activity and may require showing your work as well. Homework assignment are individual, you and your lab partner need to both turn them in separately even if you work on them together.

* Participate in an online forum discussion (typically 3 quality posts or more) of each module on the Cisco Netacad site. See the xref:forum-posting:index.adoc[forum posting page] for details. (up to 10 points each module based on quality)

TIP: Discussion forum posts are usually worth a larger portion of your final grade than most students expect! If you have not done discussion posts in one of Dr. Franske's classes before, or you want to try and score better on discussion forum postings, be sure to check out the xref:forum-posting:index.adoc[instructions for participating in forum discussions and example posts]!

== Participation Activities
Any participation activities completed in the course will go here. This falls into the participation category of your course grade.

* For each topic you need to meet with the instructor at least once to check on your status and understanding of the topic. Each meeting will be worth up to 10 points.

== Topic Assessments
You are responsible for completing an online assessment for each topic. These fall into the topic assessments category of your course grade. 

== Final Exam
You are responsible for completing a final exam, this will go into the regular final exam category of your course grade.

== Course Project (Case Study)
The course project will take the place of the final skills exam in this course and will allow you and your lab partner to continue to experiment with one of the topic areas covered in the course. You will need to present your project in a presentation/demonstration to the class which is expected to last 10 minutes and you will need to write and submit project report.

The project should be related to one of the three main units covered in the course. You may either expand on one of the tools that we used in the course or explore a different tool in the same topic area. Your project plan should be approved by the instructor. Remember that the project is 15% of your final grade so it is expected to be a substantial amount of work. 

=== Presentation Tips

* Presentations should be very close to 10 minutes in length. While there is not a part of your score that is directly tied to timing if they are much longer or shorter you probably have either over-covered or under-covered what you did (or didn't do enough work) which will definitely show up in your score.
* I suggest spending about half the time giving some background on your project (why you chose it, what are the key things you learned, what all did you do). You can have slides for this if you'd like.
* If you use slides I normally suggest no more than one slide per minute of presentation time (excluding a title slide) so probably stick to only about 5 slides of content. Also, follow good presentation tips for using slides (don't make them overly complicated, don't try to put too much information on one slide, don't read your slides to us as part of your presentation, etc.) There are lots of good resources online that talk about creating effective presentation slides. Two examples are: https://edu.gcfglobal.org/en/powerpoint-tips/simple-rules-for-better-powerpoint-presentations/1/ and https://www.unl.edu/gradstudies/connections/tips-creative-effective-powerpoint-presentations
* I suggest spending the other half of the time giving a demonstration about some part of your project. Don't try to show off everything you did, cramming 3 weeks of work into 5 minutes is not possible. Pick one specific part of your project that you can demonstrate in 5 minutes and show that. You're not trying to give a "how-to" presentation so you don't need to show every step. Just give people an idea of what you did in your project. Stage things ahead of time and skip steps as needed to keep on time.


=== Case Study Lab Report Tips/Requirements

* The format is the same as a regular lab report (what you did, problems you had, how you tested, and what you learned) but the report must be much longer (about 1600 words which is about 4 pages single spaced) because it includes 2-3 weeks of work. It should be clear how you spent the three weeks and that it really was the equivalent amount of work as three weeks of regular classwork.
* You should thoroughly describe what you did (not exact steps, but an overview of the major things you accomplished), and what new things you learned by doing the project.
* It should be clear how the project relates to one of the topics from class.
* This should also be written like a paper explaining your project so don't include a bunch of lists, etc. which are just there to fill space as that will not produce a quality report.

=== Project Grading

There will be two primary components to your grade for the project, a lab report and a presentation.

You will be turning in a lab report using the same format you have used for other lab reports in the class but it will be longer as this is a much more substantial project. Lab reports for this project should be about 1600 words (this is about 4 pages single spaced) and include all the regular sections of a lab report (what you did, what problems you had, how you tested, and what you learned. The project lab report will be worth 100 points.

In addition you will receive a grade on a 10 minute presentation to the class. The presentation should be interesting, engaging, informative, and factually correct. It is a good idea to show off your actual work as much as possible (not just talk about it) so you are strongly encouraged to find a way to demonstrate something "live" during the presentation.

The presentation score is comprised of:

* Topic Content (30 Points)
** Was the topic appropriate for the course project? Was the content presented accurate and did it provide a good overview of the topic and the work done? Was the amount of work done appropriate for a large course project?
* Presentation Skills (30 Points)
** How well did the group do ''explaining'' the content? Were they able to adequately answer appropriate questions from the class? Was the presentation professional and well prepared?
* Engagement (20 Points)
** How well did the group engage the class in their presentation? This could include getting or asking questions of the class, using appropriate visual aids, etc. How well did the group express excitement and interest in the topic of their presentation?
* Overall Quality (20 Points)
** Did you learn something or get something clarified in your mind? Did you feel listening to this presentation was worth your time? Was this a "good" presentation? Are you interested to learn more about this topic having heard this presentation? Do you have a good understanding of how you could use this to solve future problems you come across?

Finally, a small portion of your grade for the project presentation (10% of the presentation score) will be writing a short review of each of the other project presentations. These are not simply participation points for filling out a review, your review will be graded for quality so be sure you listen carefully and provide useful feedback in your review.

== Archived Labs
*This section contains information about labs that have been used in this class in the past. You are NOT responsible for completing these labs.*

=== Voice over IP (VoIP) Labs

--
NOTE: If you need additional time to complete these labs you may need to work in the B143 lab instead of our normal B144 lab. In that case be sure to read the xref:lab-asterisk-b143.adoc[B143 lab modification addendum] which explains changes you need to make to the lab setup to make things work in B143.
--

==== Introduction to VoIP with Asterisk Lab
Find instructions for the xref:lab-asterisk-introduction.adoc[Introduction to VoIP with Asterisk Lab here].

==== VoIP Provisioning, Voicemail, and SIP Labs
Find instructions for the xref:lab-asterisk-provvmsip.adoc[VoIP Provisioning, Voicemail, and SIP Lab here].

==== VoIP T1 and PSTN Access Lab
Find instructions for the xref:lab-asterisk-t1pstn.adoc[VoIP T1 and PSTN Access Lab here].

==== VoIP GUI Asterisk Configuration Lab
Find instructions for the xref:lab-asterisk-guiconfig.adoc[VoIP GUI Asterisk Configuration Lab here].


include::program-info:ROOT:partial$stdfooter.adoc[]