= ITC-2300 VoIP Labs Switch and Router Configurations

== Notes

Don't forget to modify for the information specific to your Pod:

* Change the hostname of both the Router and Switch to include your Pod ID
* Change the IP Address on the Router Fa0/0 interface to the correct IP for your pod
* Change the extension numbers/phone numbers to those appropriate for your pod
* Read through all lines in the configurations, especially comment lines starting with a !

You may want to make some additional changes for administration ease:

* Set an enable secret
* Setup a username and secret on both devices
* Setup SSH on both devices

== Basic Router Configuration

----
hostname PodX-Router
!
interface GigabitEthernet0/0/0
 ip address 192.168.1.5 255.255.255.0
 no shutdown
!
ip route 0.0.0.0 0.0.0.0 192.168.1.1
!
----

== Basic Switch Configuration

----
hostname PodX-Switch
!
vtp mode transparent
!
spanning-tree portfast default
!
----

== Adding ISDN <-> SIP Gateway Support to the Router

--
NOTE: You will not need this configuration until you get to the T1 gateway lab.
--
These additions to the configuration of your router allow it to act as a VoIP gateway which converts a digital ISDN PRI trunk from the Public Switched Telephone Network (PSTN) to a SIP trunk which Asterisk can send and receive calls on. This means that calls sent to the router (only from the IP of our Asterisk server thanks to the ACLs) are able to be sent to the PSTN over a T1 PRI voice trunk with guaranteed quality and calls coming from the PSTN can be converted into VoIP by the router and sent on to Asterisk.

----
! Put the T1/E1 card found in slot 0 , subslot 1 into T1 mode
card type t1 0 1
!
! Setup ISDN on the router to use signaling for PRI connections to a National ISDN switch
isdn switch-type primary-ni
!
! Tell the router to synchronize the DSP clock to the T1 card
network-clock synchronization automatic
!
! Enable SIP VoIP capabilities on the router and set the router to use the correct interface for SIP signalling
voice service voip
 sip
  bind control source-interface GigabitEthernet 0/0/0
  bind media source-interface GigabitEthernet 0/0/0
!
! Configure the T1 settings for slot 0, in subslot 1, on port 0 to use the correct modes for the ISDN switch and to use all 24 timeslots in the ISDN PRI T1 connection
controller T1 0/1/0
 framing esf
 clock source line primary
 linecode b8zs
 cablelength short 110
 pri-group timeslots 1-24
!
! Send calls to any phone number received by the router (from Asterisk) to the PSTN over the T1.
dial-peer voice 1 pots
 description Calls from Asterisk to PSTN
 destination-pattern .T
 port 0/1/0:23
!
! Send calls to 510555ZZ.. numbers to the Asterisk server using SIP to route further
dial-peer voice 2 voip
 description Calls from PSTN to Asterisk
 ! change the two ZZs in the next line to match the incoming numbers for your pod (the last two characters should be periods to match any number)
 destination-pattern 510555ZZ..
 session protocol sipv2
 ! The IP in the next line should be the internal network IP of your Asterisk server
 session target ipv4:192.168.1.10:5060
 incoming called-number .T
 dtmf-relay rtp-nte
 codec g711ulaw
 no vad
!
dial-peer voice 3 pots
 description Passes inbound calls from PSTN on to dial peer 2 which will send them to Asterisk
 ! change the two ZZs in the next line to match the incoming numbers for your pod (the last two characters should be periods to match any number)
 incoming called-number 510555ZZ..
 direct-inward-dial
 port 0/1/0:23
!
----


include::program-info:ROOT:partial$stdfooter.adoc[]