= Proxmox VE Installation Lab

== IP Addressing
You will be assigning static IPs to your systems in this lab. Please use these settings:

* Subnet Mask: 255.255.255.0
* Default Gateway: 192.168.1.1
* DNS Server 192.168.1.1

[%autowidth,options="header"]
|===
|System |IP

|HV-A |192.168.1.10

|HV-B |192.168.1.11
|===

== Instructions

. VMs are located on the https://netlab.ihitc.net Netlab system, be sure you are signed in to the ITC Passport site through D2L before attempting to access this system
+
--
NOTE: You will need to make a reservation for the Proxmox Labs in this class before you are able to access the VMs. Changes will be saved between your reservations so you will be able to make multiple reservations over several days as needed to complete labs.

WARNING: If you need to split your work up across multiple reservations be sure to safely shutdown your Proxmox VMs before ending your Netlab reservation. Otherwise when your reservation ends Netlab will simply power off your VMs (without shutting them down first) which could cause data corruption.

NOTE: If you make a mistake and need to have one or both of your HV VMs erased so you can re-install Proxmox you will need to contact your instructor or the ITC lab assistant to have them reset.
--
. Boot both your Proxmox VE Server systems
. Check the available container templates on your PVE server and make sure you have downloaded the latest Debian system templates. Also download at least one of the Turnkey Linux appliance templates such as the Wordpress template.
+
--
NOTE: If you have an incomplete list of container templates it's likely the case that your system was powered off when the auto-run script went to check the list of available templates. You can refresh this list manually from the PVE command line using information from the https://pve.proxmox.com/wiki/Linux_Container#pct_container_images[ProxMox Linux Containers] page.
--
. After you have the containers downloaded go ahead and deploy a container based on the Debian template, use DHCP addressing.
. Try using the Debian container to see if it feels any different than a regular Debian VM.
. Create a Proxmox cluster for your pod named "PodX" where X is replaced with your pod letter. Do this on the Proxmox node containing your VMs, nodes to be added will not be able to have VMs until after they are added.
. Add your Proxmox server B to your Proxmox cluster.
+
--
NOTE: If you're having difficulty with this there are two critical requirements that must be met per the documentation and in the instructions from the previous lab: the hostnames of the two Proxmox servers MUST be different AND there can be no VMs on servers being added to a cluster (in this case server B is being added to the cluster). Make sure you have met both requirements.
--
. Deploy a Ubuntu container to a node in your Proxmox cluster, verify it is working
. Deploy a Wordpress server container to a node in your Proxmox cluster, verify it is working
. Try migrating one of your VMs from the last lab which is NOT powered on from one node to another node in the cluster and then powering up and verifying the VM still works
. Try migrating one of your Linux containers from one node to another node in the cluster. Note that containers will be powered off while being moved and will then be restarted once the move is complete.
. Setup some kind of remote access to one of your VMs. That could be Remote Desktop to a Windows VM or SSH to a Linux VM.
. Use PC-C to open a connection directly to the VM with remote access (SSH to Linux or Remote Desktop to Windows)
. Try migrating the VM with a remote access connection open (while it is powered on) from one node to another node in the cluster. Make sure you can maintain connectivity and work on the VM the entire time the VM is being migrated.
+
--
NOTE: You will need to remove any CD images from the system before it can be migrated.
--
. Try modifying an existing VM by adding extra storage, in the form of an additional virtual disk and ensure you can see and use the space inside your VM
. Try modifying an existing container by adding extra storage, in the form of an additional mount point and ensure you can see and use the space inside your container
. Try cloning one of your VMs
. Safely shut down all your containers and VMs
. Safely shutdown your Proxmox VE servers
. End your Netlab Reservation


include::program-info:ROOT:partial$stdfooter.adoc[]