name: Publish to GitHub Pages Directly with NPM
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Chicago"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Antora Globally
        run: npm install -g @antora/cli@3.0.1 @antora/site-generator@3.0.1 
      - name: Install Lunr locally  
        run: npm install @antora/lunr-extension
      - name: Generate Site
        run: antora antora-playbook.yml
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
          cname: info.ihitc.net